### PR TITLE
LPS-93315

### PR DESCRIPTION
**Pull request by Alec-Shay**
https://issues.liferay.com/browse/LPS-93315

Hi @moltam89,

Can you take a look at this implementation for LPS-93315? This change is to allow scheduled publishes to use times that can be scheduled in different time zones, rather than always defaulting to the user's time zone.

We are being pushed to "fix" this on our end, as currently there is no way for Liferay to handle staging publishes across different time zones (that may need to have their times managed separately -- for example, if some would follow daylight savings time and some wouldn't).

To accomplish this, I copied the time zone selector UI element used by the Calendar portlet and added new API that sets the time zone for the schedules created for Quartz. Quartz itself (as I've seen in my own testing) already compensates for time changes and such, so all the changes here need to do is propagate the time zone information where needed to achieve the goal of scheduling for different time zones.

Apologies in advance if you think this should be reviewed by perhaps a different component team (such as the core component), since even though the code is in the staging classes, it is sort of only tangentially staging code, that's mostly just dealing with the scheduler and time zones. Just let me know and I can send it to someone else if needed. Thanks.

### CODE REVIEW

**Comment by Alec-Shay** [comment]
ci:test

**Comment by Alec-Shay** [comment]
ci:retest

**Comment by moltam89** [comment]
Hi Alec,

I'm not sure either if I'm the right person to review this, I'll do my best to understand the changes and forward it to another team if necessary.

In Hungary we have Friday and Monday off, so I can only get back to you on Tuesday.

Best,
Tamás

**Comment by Alec-Shay** [comment]
Hi Tamás,

I understand, whatever you think is best. Thank you for letting us know, I appreciate it.

**Comment by moltam89** [comment]
Hi Alec,

I think I found a problem while I was testing.
I started a new publication and changed the Time Zone to "(UTC -02:00) Fernando de Noronha Time".

It worked fine with Local Staging, a new publication was scheduled to run after 2 hours.

However, with Remote Staging, I got the following error:
"Error:A wrong end date was specified, the scheduled process will never run."

Also, I got the same error, when I was using Local Staging with a Publish Template.

Could you please check these use cases?

Thanks,
Tamás

**Comment by Alec-Shay** [comment]
Hi Tamás,

Thanks for taking a look at this and finding this. I will look into that soon.

**Comment by Alec-Shay** [comment]
I looked into those issues, and had to make some changes. I'm resending this to avoid making this PR too confusing from amends: https://github.com/moltam89/liferay-portal/pull/493

**Pull request closed without merging**
