### PR TITLE
[TECHNICAL-SUPPORT] LPS-89294

### PR DESCRIPTION
**Pull request by Alec-Shay**
Resent from: https://github.com/moltam89/liferay-portal/pull/496#issuecomment-495571662

Here are the latest notes from @knchau on this:

> https://issues.liferay.com/browse/LPS-89294
> 
> The issue is how we log connection exception errors. The proposed fix changes how we would log connection errors for all http services reached by the server. If there's a ConnectException thrown, only a one-liner Connection error + cause will be logged. A debug logging is added for these exceptions too, if stack trace is needed, set logging to debug level for the class which threw the ConnectException.
> 
> Previous pr: https://github.com/moltam89/liferay-portal/pull/496#issuecomment-495571662 indicates that this ticket should handle logging related changes. 
> 
> This ticket does not affect LPS-94690 and LPS-94690 does not affect this ticket but LPS-94690 needs this ticket because it will make the error thrown in LPS-94690 clean. There is no code conflict between these two tickets, so I think it should be safe to move forward.

Please let us know your thoughts on this. Thanks.

### CODE REVIEW

**Comment by Alec-Shay** [comment]
ci:test:relevant

**Comment by Alec-Shay** [comment]
ci:test:sf

**Comment by Alec-Shay** [comment]
ci:test:relevant

**Comment by moltam89** [comment]
Hi @knchau, @Alec-Shay ,

It still seems to me that not all the files have been regenerated.
E.g. I can't see any journal related changes.

If I'm not very much mistake LPS-95413 changed the service_http.ftl file last time, where more files were generated.

Best,
Tamás

**Comment by knchau** [comment]
@moltam89, I'm sorry I have only been building in portal-impl and didn't realize there were other packages containing ServiceHttp files. I'll resend the changes to Alec. Thanks!

**Pull request closed without merging**
