### PR TITLE
[TS] LPS-87629

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @nellyliupeng

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:staging

**Comment by jonathanmccann** [comment]
Other tests passing here - https://github.com/wanderlast/liferay-portal/pull/11#issuecomment-440893478

**Comment by moltam89** [comment]
Hi @nellyliupeng,

on previous pull requests, I read that this issue is not reproducible in master because "due to the introduction of changesets fixing the underlying problem".

Could you please elaborate on how changesets are fixing this issue?
I think changesets don't really have affect on the initial publication process, as we only start collecting the changes with changesets after staging was enabled.

Thanks,
Tamás

**Comment by nellyliupeng** [comment]
Hello @moltam89,

After testing in master when local staging is turned on, both _startDate and _endDate in `PortletDataContextImpl ` return null every time, and thus date ranges are not used nor introduced in the query for retrieving content at all. 

The check in the fix wouldn't do much effect on master, but it does in 7.0.x branch to prevent an invalid query from being introduced when _endDate is null and _startDate is not. I also found out that this would affect retrieval of other staged contents such as ADTs, site teams, page comments..

Best regards,
Nelly

**Comment by moltam89** [comment]
Hi @nellyliupeng ,

so if I understand it correctly, something fixed this issue in master.
Generally, I think it's better to find the fix and backport it, than adding a fix to master because in an older branch there is a bug.

It seems wrong to me, that in 7.0 the _startDate is not null during the initial publication.
Also, to me it make sense to create a date range query with only the _startDate set.

I'd rather not merge this fix, until we're absolutely sure that there isn't a better way to solve this issue.

Thanks,
Tamás

**Comment by nellyliupeng** [comment]
Good morning @moltam89!

Thank you so much for looking over this issue.

I wanted to clarify more, changesets in master seem to keep a better track of staged content modified since last publication, and thus do not make use of dynamic queries to retrieve content based on modified dates. Since 7.0.x does not have this feature, it relies on the values of _startDate and _endDate to build the dynamic queries and retrieve the contents, but currently there's no check present that prevents an invalid query from being formed. This prevents certain content to be exported to staging.

I also wanted to add, that in 7.0.x, the _startDate does start with null the first time local staging is turned on and thus retrieves contents properly. But the issue appears from the second time and onwards, where it doesn't know how to better keep track of when it was last modified (and thus the scenario where _startDate is not null but _endDate is).

> Also, the [validateDateRange()](https://github.com/liferay/liferay-portal/blob/master/modules/apps/export-import/export-import-service/src/main/java/com/liferay/exportimport/internal/lar/PortletDataContextFactoryImpl.java#L339) method seems to imply we should have both a startDate and endDate, otherwise throw an exception.

For reference, these were the sources I was looking over: 

- https://dev.liferay.com/ca/develop/reference/-/knowledge_base/7-1/breaking-changes#changed-the-from-last-publish-date-option-in-staging
- https://issues.liferay.com/browse/LPS-81695

Please let me know if more clarification is needed, thank you so much once again!

Best regards,
Nelly

**Comment by moltam89** [comment]
Hi @nellyliupeng ,

about changesets:
I still don't think that changesets are related to this issue. You're right, with changesets using the default from last publish date publication, we don't need to create complex queries, as it is stored which entities were created/modified since the last publication.
However, during the initial publication, when local staging is turned on, we can't rely on the changesets yet, we need to run the queries the same way as in 7.0.

Do you know why the _startDate is not null when the staging is enabled for the second time?
Probably that's the root cause of the issue, I don't understand why we need to set a _startDate for an initial publication, when we want to copy everything from the Live group to the newly created Staging group.
Do you know why only some portlets are affected and other portlets work properly?

Checking the linked validateDateRange() method, I start to think that you're right and the logic of the current fix is good, however we're actually hiding the root cause of the issue.

Thanks,
Tamás

**Comment by nellyliupeng** [comment]
Good morning @moltam89,

Thank you once again for your reply! To answer your question, the reason why _startDate is not null in the subsequent iterations is because it's populated by the time it was last published. However, then the situation arises where _endDate is null, which causes an invalid dynamic query to be formed. As date range should contain both valid start and end dates, this fix attempts to prevent that improper query. Other portlets are affected as a result of the same scenario, where their startDate is populated by the time they were last published.
Please let me know if more clarification is needed,

Best regards,
Nelly

**Comment by AngeloJ** [comment]
Hi @moltam89, If more clarification is needed let's set up a call to discuss, possibly for Thursday afternoon your time.

**Comment by moltam89** [comment]
@AngeloJ ,

unfortunately I won't have time this week, as I'll need to leave early on Thursday and Friday as well.
Maybe Tuesday?

@nellyliupeng 

I took another look into this issue and I still don't think that the current fix will solve the root cause.

Last published dates are stored in the portletpreferences table, for the Staging Site.  As the Staging Site is deleted when Local Staging is disabled, it shouldn't matter that Staging was enabled and disabled previously.
This works properly (I was testing in 7.0.x) e.g. for the JournalPortlet, when Local Staging is enabled, a new portletpreference is created with the last publish date and when Local Staging is disabled, this portletpreference is deleted.

However, as far as I can see, this part doesn't work well for the PortletDisplayTemplatePortlet. The portletpreference  storing the last publish date doesn't belong to the Staging Site. Actually, it doesn't belong to any of the Sites (the ownerType should be 2, which means Group).
This is problematic, as multiple Sites share the same last publish date.
Let's say we enable Staging (Application Display Templates enabled) on SiteA and SiteB. If we create ADTs on both Site, and publish SiteA to Live, when we publish SiteB, the ADTs won't be published, as the last publish date was updated incorrectly when SiteA was published.

The current fix will solve this problem only during the initial publication, but the same issue can happen if multiples Sites are Staged.

Thanks,
Tamás

**Comment by moltam89** [comment]
**Note:**
I think this issue can be related:
https://issues.liferay.com/browse/LPP-28958

On this LPP, the PortletDisplayTemplatePortlet was listed.

**Pull request closed without merging**
