### PR TITLE
[TECHNICAL SUPPORT] LPS-96983 Update the ID of the imported Data Providers referenced by Text fields.

### PR DESCRIPTION
**Pull request by natocesarrego**
Hey @moltam89,

Do you remember of our discussion on [PTR-937](https://issues.liferay.com/browse/PTR-937)? This pull request is the outcome of our discussion. Can you please review it?

Thanks in advance.

### CODE REVIEW

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by moltam89** [comment]
Hi Renato,

Sure, this seems good to me I've forwarded it to Dani: https://github.com/danielkocsis/liferay-portal/pull/842

I've changed the condition a little bit, I think the two conditions are the same.
Let me or Dani know if I was wrong.

Cheers,
Tamás

**Comment by natocesarrego** [comment]
No problem, @moltam89. 🙂 

Thanks a lot!

**Pull request closed without merging**
