### PR TITLE
[TECHNICAL-SUPPORT] LPS-94690

### PR DESCRIPTION
**Pull request by Alec-Shay**
Hello @moltam89,

Here is a fix intended to correct the errors with remote Staging addressed previously with this pull request (but now separated out from the logging changes in [LPS-89294](https://issues.liferay.com/browse/LPS-89294): https://github.com/moltam89/liferay-portal/pull/496

Notes from @knchau:

> https://issues.liferay.com/browse/LPS-94690
> 
> The issue is when the site is staging. At every page load of the Control Panel, the local server would send a request to the remote server. This can cause the site to hang because the request is sent in https://github.com/SamZiemer/liferay-portal/commit/066cdaddcb673cb86fa7b8c0d124bc94cb730392#diff-2db79331dcd02f15d22749213538877fL46. The timeout can take 30 seconds.
> 
> My changes move the logic to the backend in a thread using the quartz scheduler. The quartz scheduler monitors the remote server's connection and updates the remote display URL. 
> 
> https://github.com/SamZiemer/liferay-portal/commit/180e3c4977dd28f4c27ca94ff4e61eef95e806db initially caches the remote URL when remote staging is enabled. 
> 
> https://github.com/SamZiemer/liferay-portal/commit/8ceb788b52d9bf3f609318ab36613cacf750b317#diff-9bf2f5518a6bd236e54fde2bb44520c4R119 monitors the connection and updates the cached remote URL. This value will be updated into typeSettingsProperties. If there is an error, it will not cause the site to hang instead it will throw an error. 
> 
> The updated/cached display URL is referenced in the jsp instead of pinging the remote server to populate the href.
> 
> https://github.com/SamZiemer/liferay-portal/commit/efb194a517f9346b90c17e164b2c173974b25f22 stores data into Message so it can be referenced in StageMessageListener.java. It will update the group's value at every page load of the Control Panel.

Please let us know what our thoughts on this one are when you can. Thanks again for looking at this for us.

### CODE REVIEW

**Comment by Alec-Shay** [comment]
ci:test:relevant

**Comment by Alec-Shay** [comment]
ci:test:sf

**Comment by moltam89** [comment]
Hi @knchau , @Alec-Shay ,

I'm a bit confused, it seems to me that we have a scheduler task which runs periodically, but doesn't really do anything, as the message doesn't contain the group value.
Am I missing something?

Thanks,
Tamás

**Comment by knchau** [comment]
@moltam89, I passed the group value through the site_administration_header.jsp, so it should populate the message with every page load of the Control Panel or every 30 seconds.

**Comment by moltam89** [comment]
Hi @knchau ,

So if I understand it correctly, first we need to navigate to the Staging Site, which populates the values.

In LPS-94690 @zsoltbalogh asked not to ping the remote site from the browser, see his [comment](https://issues.liferay.com/browse/LPS-94690?focusedCommentId=1836198&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1836198).

I talked to @danielkocsis as well, the scheduler task should check all the staging groups and update the live URLs if necessary.
It should be enough to run this task in every hour, or we could also make this configurable.

Best,
Tamás

**Comment by knchau** [comment]
Hi @moltam89,

We would not need to navigate to the Staging Site to generate the live URL value since it's generated and saved into typeSettingsProperties when remote staging is enabled. But currently, live URL will also update when reloading the Control Panel or calling scheduler task. 

I've removed the pinging from the [jsp](https://github.com/moltam89/liferay-portal/pull/502/commits/0acf4185b6595fc2498b83deb9a8b5157f78f8ad#diff-2db79331dcd02f15d22749213538877fL46) so it doesn't cause the site to hang. The Remote Site live URL currently regenerates at every reload of the Control Panel. But without sending the message from the Control Panel like I did, clicking Remote Site in the Control Panel would take us to a 404 page until scheduler task is called to update the live URL - is that expected? If not, how should this be handled?

The message values are populated when Control Panel is loaded due to [sendMessage](https://github.com/moltam89/liferay-portal/pull/502/commits/b82ddc909cf3a987af96dddd63c96e4a041273e2#diff-85d5943f016624b8ad04245c8b434faeR31) which contains the group, layout, and user values. The message values are used to update that live URL so I think I need to pass these data through message but I'm unsure where that should happen to keep the data updated and not pinging each browser session.

I also need further elaboration regarding:
> scheduler task should check all the staging groups and update the live URLs if necessary

Can you expand on how this should be implemented? If we are using the staging group to monitor the remote live, can we ping the remote server from the backend and update the live URL as necessary using GroupServiceHttp.getGroupDisplayURL? 

Thank you!

**Comment by danielkocsis** [comment]
Hey @Alec-Shay and @knchau,

@moltam89 asked me to take a look on this as well, and I have a question. Can you help me to understand how the logic in the message listener is being invoked? My understanding is that you want to periodically invoke a the logic without any actual user interaction, so I am not sure why do you need a new destination? Please see CheckSystemEventMessageListener for further reference!

The other thing is the logic itself, there shouldn't be any dynamic attributes since the list of remotely staged sites can vary over time, and it is not correct to pass a pre-defined list once you schedule the task, but to determine it dynamically in the beginning of every task execution OR keep a shared state StagingLocalService.enableRemoteStaging/disableRemoteStaging can maintain. If you chose the 1st option and determine it dynamically, then you need to iterate over companies/groups (or create a dynamic query instead) and get the list of remotely staged sites and do the check for all!

I hope it helps,
Daniel

**Comment by knchau** [comment]
Hi @danielkocsis, 

The message listener was being invoked periodically and when the message was sent by reloading the Control Panel. But you are correct, the logic should not be invoked through any actual user interaction. I just did not know how the listener was to determine it dynamically, but your comment did help!

I've sent in a new pull request with your suggestions in mind: https://github.com/SamZiemer/liferay-portal/pull/612

Thanks!

**Pull request closed without merging**
