### PR TITLE
[TECHNICAL-SUPPORT] LPS-86368

### PR DESCRIPTION
**Pull request by Alec-Shay**
Relevant tickets:
https://issues.liferay.com/browse/LPP-31765
https://issues.liferay.com/browse/LPS-86368

If a document is published to live (or imported) that has had more than one version increment since the last time, then the modified date for the DLFileEntry in the database (in the DLFileEntry table) will be updated with the current timestamp, instead of the date the document was actually modified. This is because, Liferay treats subsequent imported versions as updates, and while the modifiedDate was technically updated at the time of the document update (so before the export), it did not happen during the "update," so it assumes the modifiedDate still needs to be changed.

This change addresses the issue by attempting to more carefully tune when the update to the modified date happens by avoiding it during imports, unless it is absolutely necessary because there is no modified date already present.

Unfortunately, because the `hasSetModifiedDate()` method only seems to consider updates to the modified date that occurred within the same update process, that means it will not accurately determine whether the modified date is already set in cases like this -- so it seems like actually checking more directly whether the modified date is null is also necessary.

Because of this, the code now visually looks very redundant -- and because I'm not sure whether this actually affects a whole ton of types of StagedModels, I'm not sure if this is really the best approach for a fix either. However, I wasn't sure of a better way to do this, because it seems like whatever is done, there is always going to have to be a change done to the persistence because that's where the change is happening, and `updateImpl()` is going to need to be called either way. But I am curious to know whether you have any other thoughts on this or alternative suggestions, because I was a little unsure of where to go with this one for a while.

Thanks in advance!

### CODE REVIEW

**Comment by Alec-Shay** [comment]
ci:test

**Comment by moltam89** [comment]
Hi @Alec-Shay ,

have you managed to reproduce this issue with other entities as well, or were you testing DL only?

I was checking Blogs (I wanted to keep it simple) and as far as I can see, it works properly.
The serviceContext created (with the proper modifiedDate) in https://github.com/liferay/liferay-portal/blob/master/modules/apps/blogs/blogs-service/src/main/java/com/liferay/blogs/internal/exportimport/data/handler/BlogsEntryStagedModelDataHandler.java#L230 is stored by the ServiceContextAdvice class, and used by the persistence layer.

**Note:**
I haven't had time to fully investigate this issue, sorry if I miss something.

Thanks,
Tamás

**Comment by Alec-Shay** [comment]
Hi @moltam89,

Thanks for taking a look at this already. I actually didn't reopen this pull request because I realized that, when I tried to rebase it before I sent this, and I somehow missed a line (import statement for ExportImportThreadLocal) so I needed to resend anyway.

I had thought it might be reproducible for some other type of (versioned) entity too, but was not able to find a use case for it with anything other than documents. I think it stems from the fact that versions for DL are handled differently, with their own table. So if there is a way to do it that does not have to affect other PersistenceImpl classes, I think that would definitely be preferable. I'll take a look at the ServiceContext and see if I can get it behaving right with that instead.

**Comment by Alec-Shay** [comment]
@moltam89 Actually, I forgot, but this was I believe something I tried before when fixing this. I think the problem with going about it that way is that, because when importing multiple versions, it calls this: https://github.com/liferay/liferay-portal/blob/master/modules/apps/document-library/document-library-service/src/main/java/com/liferay/document/library/internal/exportimport/data/handler/FileEntryStagedModelDataHandler.java#L634

This calls code that treats it almost like a regular (new) update for the DLFileEntry, and it does not keep the ServiceContext. So then by the time it gets to the PersistenceImpl classes to update the new DLFileVersion and the DLFileEntry together, it no longer has that information and falls back to updating with the current date. So because of this, I unfortunately wasn't sure of a way to use the ServiceContext to fix it without also updating the PersistenceImpl.

**Comment by Alec-Shay** [comment]
Hi @moltam89,

Do you have any other thoughts on whether a different kind of fix may be more viable for this? I am still reluctant to go with this, though I still don't really see a different way that works.

For reference I can send a new pull request too if that's better with the rebase error fixed, I just don't know whether it matters at this point. Please let me know what you think when you can.

**Comment by moltam89** [comment]
Hi @Alec-Shay ,

sorry, I haven't been able to find time for this issue yet.
I'll try to give you an update tomorrow.

Thanks,
Tamás

**Comment by Alec-Shay** [comment]
Hi @moltam89,

No worries. Thanks for the heads-up.

**Comment by moltam89** [comment]
Hi @Alec-Shay ,

is this issue only about staging?
I thought it's also reproducible with LAR export/import, but there is an _ExportImportThreadLocal.isStagingInProcess()_ check before the problematic __overrideFileVersion_ method call you mentioned.

If the problem only comes when the __overrideFileVersion_ method is called, I think using the serviceContext should fix the issue.
Can't we push and pop the serviceContext manually like we do it for blogs?https://github.com/liferay/liferay-portal/blob/master/modules/apps/blogs/blogs-service/src/main/java/com/liferay/blogs/internal/exportimport/data/handler/BlogsEntryStagedModelDataHandler.java#L273

Thanks,
Tamás

**Comment by Alec-Shay** [comment]
@moltam89 Hmm, I hadn't realized that's how it was working for Blogs. I am going to take a closer look at that to confirm whether it can work in this case as well soon. Thanks for pointing that out.

**Comment by Alec-Shay** [comment]
@moltam89 I looked into this more and I'm pretty sure you're right about that. Originally I thought I had reproduced the issue with LAR imports as well as Staging, but I went back and found that's not the case, because of that check you referenced. So I suppose the fix could just apply within that scope.

I also found that it should be able to work pushing and popping the way you mentioned. Thanks again for finding that. I'll go ahead and a new proposal for a fix soon.

**Comment by Alec-Shay** [comment]
Re-sent to: https://github.com/moltam89/liferay-portal/pull/446

**Pull request closed without merging**
