### PR TITLE
LPS-74467 Adding (Staging) suffix to staged site roles

### PR DESCRIPTION
**Pull request by balazssk**
Hi Tomcsi,

Can you please have a look at this?

Thanks,
Balazs

### CODE REVIEW

**Comment by balazssk** [comment]
ci:reopen

**Comment by balazssk** [comment]
ci:retest

**Comment by balazssk** [comment]
Hi Tomcsi,
The above failures look unrelated to my changes. Can you please double check?
Thanks

**Comment by moltam89** [comment]
Hi Balázs,

I can't see the connection between your fix and the failing tests either.

Could you please forward this to @giros, as he is already familiar with the issue and I won't be able to review this in the near future.

**Note:**
_if (group.isStaged() && !group.isStagedRemotely() && group.isStagingGroup()) {_
I think this is the same as
 _if (group.isStaged()) {_

You can search e.g. for **isStaged** on Grow, to see a table about these methods.

Thanks,
Tamás

**Pull request closed without merging**
