### PR TITLE
[TECHNICAL SUPPORT] LPS-99287 Use the DDMStructure uuid during export/import operations instead of typePK (that stores structureId)

### PR DESCRIPTION
**Pull request by jorgediaz-lr**

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
Unique failures seems to be unrelated to my changes, as they are related to frontend (npm and yarn)

**Comment by moltam89** [comment]
Hi @jorgediaz-lr ,

Probably I'm not the right person to review this, as the fix contains application specific logic only.
Could you please send this to someone from the forms team instead?

**Note:**
Taking a quick look at the fix I don't really understand why it is needed to use the structure's UUID. 
I think it would be easier to use the newPrimaryKeys map to obtain the structure's primary key during the import.

Thanks,
Tamás

**Comment by jorgediaz-lr** [comment]
Thank you, @moltam89

**Comment by jorgediaz-lr** [comment]
I have sent it to workflows component team, see: https://github.com/inacionery/liferay-portal/pull/204

I have also removed all UUID stuff.

Thank you

**Pull request closed without merging**
