### PR TITLE
[TECHNICAL SUPPORT] LPS-54392

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-54392

Changes:
 - **First commit https://github.com/moltam89/liferay-portal/pull/433/commits/e428699c311974887d14ece04ca8089707ca8d3c:** in case of  `preloaded=false` call default methods of parent class, it will search objects in specified group, parent groups and in case of not finding the objects everywhere inside the company. Objects with ` preloaded=true` will be handled using current logic.
 - **Second commit https://github.com/moltam89/liferay-portal/pull/433/commits/76d2c595ee26f83a05eea270586ea8fa7456a10a:** now, the groupId of missing references are mapped to `portletDataContext.getScopeGroupId()`, in case of finding the missing reference in other group, update the mapping to the correct groupId of found object

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test

**Comment by jorgediaz-lr** [comment]
ci:test

**Comment by jorgediaz-lr** [comment]
@moltam89 seems errors are unrelated to export/import functionality

**Comment by moltam89** [comment]
Hi @jorgediaz-lr ,

- **First commit**: 
Do I understand it correctly that the logic is basically the same as in my previous pr (https://github.com/matethurzo/liferay-portal/pull/968)?
If I remember correctly, Máté rejected that pr because it's not complete, as the preloaded entities won't be found.
- **Second commit:**
I'm not sure if it's a good idea to update the groupIds map here. Let's say we referenced content from the Global Site, but we found it during the import in a different simple Site, wouldn't it cause problems if we update the map?
Also it's a bit weird that we only update the groupIds map this way for these 4 entities.

Thanks,
Tamás

**Comment by jorgediaz-lr** [comment]
Hi @moltam89 

About first commit, for preloaded entities we can add some kind of logic that search them in parent and global groupIds, but searching in the whole company is not possible because all finders uses groupId in order to search the preloaded entry.
It will be necessary to create a new finder using companyId and preloaded key or search the preloaded entry in all groups

About second commit, I am only updating the mapping in case of external groupId was mapped to "portletDataContext.getScopeGroupId()". All groupIds of missing references are mapped to the target site of import operation because of this fallback code:
  - https://github.com/moltam89/liferay-portal/blob/8886c557d3888f307e34df07039acecf12fdc978/modules/apps/site/site-impl/src/main/java/com/liferay/site/internal/exportimport/staged/model/repository/StagedGroupStagedModelRepository.java#L145-L149

If we don't change groupId mapping, we have other problems during import operation because for example in JournalArticle, data handlers get the original groupId+articleId and translate them using portletDataContext hashmaps into targetGroupId+targetArticleId.
If targetGroupId value is not consistent with targetArticleId groupId, errors and inconsistencies are produced.
Other idea could be to create a new hashmap that given the class-pk of an objects, it returns its groupId. What do you think?

In order to discuss this pr, can I reach you by slack/skype/hangouts?

Thank you

**Comment by jorgediaz-lr** [comment]
*Update:* About my previous comment https://github.com/moltam89/liferay-portal/pull/433#issuecomment-411392292: 

> If we don't change groupId mapping, we have other problems during import operation because for example in JournalArticle, data handlers get the original groupId+articleId and translate them using portletDataContext hashmaps into targetGroupId+targetArticleId.
> If targetGroupId value is not consistent with targetArticleId groupId, errors and inconsistencies are produced.

I have done some checks and the only problematic entity is JournalArticle.

I am going to remove this logic and try other approach.

About preloaded entities, please, have a look to first paragraph of my previous comment https://github.com/moltam89/liferay-portal/pull/433#issuecomment-411392292

**Comment by moltam89** [comment]
HI @jorgediaz-lr ,

I agree that it would be difficult to find a general solution for the preloaded entities.

I think you should the pull request with the new approach to Máté, as he is going to make the final call anyways.

Thanks,
Tamás

**Comment by jorgediaz-lr** [comment]
Thank you @moltam89 

I am going to do some changes and I will send it to Máté

Regards,
Jorge

**Pull request closed without merging**
