### PR TITLE
J cords lps 98088

### PR DESCRIPTION
**Pull request by joshuacords**
https://issues.liferay.com/browse/LPS-98088

Resending after adding Bookmarks. Previously sent here: https://github.com/moltam89/liferay-portal/pull/509

**Problem**: Changes from [LPS-79312](https://github.com/liferay/liferay-portal-ee/commit/aa08c6a8afb12f7515c5ba6d2c103e204b0e2b0e) uses PortletPreferences to export Blogs, WIki, Documents, and Message Boards - however it only references the individual checkboxes (the ones that can be seen after clicking "Change"). This approach didn't take into account the master checkboxes for the entire group.
**Solution**: Take into account the master checkboxes for the entire group.

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by moltam89** [comment]
Hi Joshua,

If I understand it correctly, the problem here is that LPS-79312 moved the logic which exports the data from the portlet data handler classes to the export import portlet preferences processor, however, this way we don't have the [check](https://github.com/liferay/liferay-portal/blob/master/modules/apps/export-import/export-import-service/src/main/java/com/liferay/exportimport/internal/controller/PortletExportControllerImpl.java#L425)  which prevents the data export.

Even though the current fix solves this problem, I'm not sure if this is the best option.
There are other parts in PortletExportControllerImpl which are missing from the export import portlet preferences processors, e.g. the [logic](https://github.com/liferay/liferay-portal/blob/master/modules/apps/export-import/export-import-service/src/main/java/com/liferay/exportimport/internal/controller/PortletExportControllerImpl.java#L691) which handles unstaged portlets.
Right now in master even if I don't stage the Blogs portlet, the blog entries are published to Live. I think this issue is caused by LPS-79312 as well, so we should find a solution for it.

**Note:**
I already mentioned this on the previous PR, as LPS-79312 wasn't backported to 7.0, it might be a quicker way for the customer to solve their problems in the 7.0 code base, as the fix for master seems complicated.

Best,
Tamás

**Comment by joshuacords** [comment]
Hello Tamas,

I'll look into finding what was missed by LPS-79312 - I might end up
needing more help with this, but I'll do what I can.

As far as the customer, they are on a hotfix in 7.0 that brought back
LPS-79312 and I currently don't see a workaround to bringing it back.
There's also another customer wanting a fix for this in 7.1 now:
https://issues.liferay.com/browse/LPP-34524 so it'll need to be dealt with
one way or another. :/

**Comment by joshuacords** [comment]
Hello @moltam89,

I was investigating this further and something seems very wrong with LPS-79312, in particular this [commit](https://github.com/brianchandotcom/liferay-portal/pull/62031/commits/90ca4921158e0ab372c33138eab04cb306861845#diff-de8c3a65c62ddb1305e247c713688efe) where portlet data is exported through portlet preferences. From my tests, it's not that: 

> LPS-79312 moved the logic which exports the data from the portlet data handler classes to the export import portlet preferences processor

, but rather that it duplicated this export. Following an export in process, the checks you linked ([this](https://github.com/liferay/liferay-portal/blob/master/modules/apps/export-import/export-import-service/src/main/java/com/liferay/exportimport/internal/controller/PortletExportControllerImpl.java#L425) and [that](https://github.com/liferay/liferay-portal/blob/master/modules/apps/export-import/export-import-service/src/main/java/com/liferay/exportimport/internal/controller/PortletExportControllerImpl.java#L691)) are still used and will export or not export the portlet data using [exportPortletData](https://github.com/liferay/liferay-portal/blob/3157017ec751602b540805e751ebcf0267acd279/modules/apps/export-import/export-import-service/src/main/java/com/liferay/exportimport/internal/controller/PortletExportControllerImpl.java#L654) as appropriate, but later the code also runs through [exportPortletPreferences](https://github.com/joshuacords/liferay-portal/blob/3157017ec751602b540805e751ebcf0267acd279/modules/apps/export-import/export-import-service/src/main/java/com/liferay/exportimport/internal/controller/PortletExportControllerImpl.java#L526) which will lead to the refactored code without the checks that will incorrectly publish the data.
At this point I think it's best the Staging team decides how to handle this issue as I don't understand the purpose of the LPS-79312 "Refactor" commit, so I'll open a PTR.

PS: I wasn't able to reproduce the unstaged publishing of Blogs.

**Comment by moltam89** [comment]
For future reference:
Discussion was moved to PTR-1074.

**Pull request closed without merging**
