### PR TITLE
LPS-63772 if there are subtypes, we never add the default type

### PR DESCRIPTION
**Pull request by juliocamarero**
Hey @moltam89 

maybe this change is simpler and fixes the root problem? what do you think?

### CODE REVIEW

**Comment by moltam89** [comment]
Hey @juliocamarero ,

yes, in master it's a simpler solution, actually, it was my first idea as well.

However, it won't work in 6.2.x for journal, where there is no classType for the default structure, but we can create other structures.

I'm trying to keep 6.2.x and master synchronized if it's possible, and I can imagine that there will be another type in the future where we would like to use the default type and other subtypes as well.

That's why I added the new logic, I admit it is a bit awkward, as it bypasses the fact that the default fileEntryType for Basic Document is generated with 0 as fileEntryTypeId (and groupId, companyId...).

Another solution could be to generate this weird fileEntryType with proper Id's (the default structure for journal works as expected), but it would require bigger changes, and it  couldn't be backported to 6.2.x for sure.

**Comment by juliocamarero** [comment]
Hey @moltam89 

I would keep the simplest solution in master. If anyone wants to keep both links, they need to add it in the ClassTypeReader in getAvailableClassTypes. The other logic is very awkward as you said.

For 6.2 we can do whatever you think is best for maintenance. Since we don't have the ClassTypeReaders, the solution may need to be more complex as you said.

Let me know what you think,

thank you!

**Comment by moltam89** [comment]
Hey @juliocamarero ,

ok, let's keep the simpler solution in master.

I will try to force my monster to 6.2, so journal won't stop working.
We have the getClassTypes methods in *AssetRendererFactory classes, so we can have a similar solution there.

Thanks!

**Comment by juliocamarero** [comment]
Great @moltam89! thanks!

I will send this to Brian: https://github.com/brianchandotcom/liferay-portal/pull/37031

**Pull request closed without merging**
