### PR TITLE
LPS-74467 adding (Staging) to Staged Sites descriptiveName

### PR DESCRIPTION
**Pull request by balazssk**

### CODE REVIEW

**Comment by balazssk** [comment]
ci:retest

**Comment by balazssk** [comment]
Hi Tamas,
I went through the Group.getDescriptiveName calls and couldn't find any other instance of duplicate "staging" suffixing.

**Comment by moltam89** [comment]
ci:retest

**Comment by moltam89** [comment]
ci:retest

**Comment by moltam89** [comment]
Hi Balázs,

sorry, but I still don't like this fix.
[It was on purpose ](https://github.com/liferay/liferay-portal/commit/fa0f3d429bac007655c3e8958512c07b5c4673db) to use the Live groups's name when local Staging is enabled.

The getDescriptiveName method is used several places across the portal (furthermore it can be invoked from customizations also), so it seems dangerous to me, to change it.

Can't we add the staging suffix to the place where it is displayed incorrectly?

Thanks,
Tamás

**Comment by balazssk** [comment]
Hi @moltam89 ,
The LPS you linked has some mixed feelings with me. The LPS says thet "(Staging)" should be concatenated, but the commit doesn't do that. I don't see any reasoning behind this difference.

My opinion is still that we should keep the String manipulation on the backend side, forwarding various flags to the frontend is not clean.

**Comment by moltam89** [comment]
Hi @balazssk ,

I understand what you mean, the LPS's description and the actual fix are contradicting.

In my opinion none of the ways are better than the other, as sometimes we don't care about staging and we need the Local Site's name, on other cases we need the extra information.

I'd prefer to keep the logic, as others can already rely on the current behavior. 
Could you please send your fix to somebody from the staging engineering team to judge?

Thanks,
Tamás

**Pull request closed without merging**
