### PR TITLE
LPS-131578 As an Instance Administrator, I want to be able to choose whether or not to publish content via display portlets

### PR DESCRIPTION
**Pull request by moltam89**

### CODE REVIEW

**Comment by moltam89** [comment]
ci:test:sf

**Comment by moltam89** [comment]
ci:test:stable

**Comment by moltam89** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:reevaluate:1257401_1290

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
All the unique functional failures under relevant run seem like fluke issues. Trigger second round of relevant run.

**Comment by moltam89** [comment]
ci:forward

**Pull request closed without merging**
