### PR TITLE
LPS-131534 As a Content Publisher, I want to change to a specific site pages variation by using the Site Pages Variation selector

### PR DESCRIPTION
**Pull request by moltam89**

### CODE REVIEW

**Comment by moltam89** [comment]
ci:test:relevant

**Comment by moltam89** [comment]
ci:test:relevant

**Comment by moltam89** [comment]
ci:test:stable

**Comment by JoyceWang08211** [comment]
The above failures are not related to the current commit. See details in testray results: https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1558281585

cc @moltam89 and @gaborlovasdotcom

**Comment by gaborlovasdotcom** [comment]
ci:test:staging

**Comment by JoyceWang08211** [comment]
The above four unique failures are not related to the current PR. 
Will investigate the test-fix for RemoteStaging#StagingRemoteLiveWebContent under https://issues.liferay.com/browse/LPS-136401

**Pull request closed without merging**
