### PR TITLE
[TECHNICAL-SUPPORT] LPS-91233

### PR DESCRIPTION
**Pull request by Alec-Shay**
Relevant tickets:

https://issues.liferay.com/browse/LPP-32941 (partly related)
https://issues.liferay.com/browse/LPS-91233

Resent from: https://github.com/moltam89/liferay-portal/pull/476

Notes from previous pull request: 

> When publishing content, there are various types of content validation that are performed, each of which may cause the publication to fail due to invalid references. Currently, we have an option in place to allow for disabling (some) layout references, although we do not have this for other types of validation that may occur.
> 
> This fix is simply adding two more such options, and making it possible to disable all of the reference validation from the DefaultTextExportImportContentProcessor call. This should help simplify workflow for users who do not necessarily want to maintain these references, as well as provide a bit more consistency for these options.
> 
> Note that language key translations still need to be generated for the new language keys. Additionally, I added the new keys following the pattern of the existing validate-layout-references-help key, although I added a commit to fix what seems like a grammatical error to me; if that is too much of a hassle to regenerate the new translations for that, though, it seems like a minor thing so maybe that doesn't need to be included necessarily.

### CODE REVIEW

**Comment by Alec-Shay** [comment]
ci:test:relevant

**Comment by Alec-Shay** [comment]
@moltam89 

I went ahead and made the change to use a ConfigurationProvider instead of using @ Reference for the ExportImportServiceConfiguration, following the way it's outlined for Components in: https://dev.liferay.com/en/develop/tutorials/-/knowledge_base/7-1/reading-configuration-values-from-a-configuration-provider

As for the language keys though, I wanted to point out what I mean by our concerns with just using gradlew buildLang on our end. Doing so generates automatic copies which, especially in the case of the change to the existing key (see https://github.com/moltam89/liferay-portal/pull/480/commits/3072969660333f8bf152e6ffa99283a5062c28af), it will actually remove the existing translations in favor of the copies when the command is run. I pushed another branch https://github.com/Alec-Shay/liferay-portal/commits/LPS-91233-2-with-buildLang to show what I mean: 

https://github.com/Alec-Shay/liferay-portal/commit/d17cdfaf328b3eaf5e7bcdf9b182137ae580519b#diff-de714f800bbb981222da172dd0559bbbR270
https://github.com/Alec-Shay/liferay-portal/commit/d17cdfaf328b3eaf5e7bcdf9b182137ae580519b#diff-de714f800bbb981222da172dd0559bbbR270
https://github.com/Alec-Shay/liferay-portal/commit/d17cdfaf328b3eaf5e7bcdf9b182137ae580519b#diff-8b3b133cf11ad7aa5092569ce87c9a0eR270

This seems problematic because it is effectively removing translations for languages that theoretically shouldn't be affected. So, we're not sure what the proper way to ensure this doesn't happen is, unless that means it's better to just drop the commit changing that key entirely.

**Comment by moltam89** [comment]
Hi Alec,

I've forwarded the pull with some minor changes to https://github.com/matethurzo/liferay-portal/pull/2492.

I double checked the language keys related commits with Máté, he said it's OK to run the buildLang task in this case as well. According to him, the translators will find the changes and take care of them.

Best,
Tamás

**Comment by Alec-Shay** [comment]
@moltam89  Ahh, alright. Thank you for checking on that.

**Pull request closed without merging**
