### PR TITLE
LPS-76111 Publishing will fail if the linked document is in the Recycle Bin

### PR DESCRIPTION
**Pull request by daviddotzhang**

### CODE REVIEW

**Comment by daviddotzhang** [comment]
ci:test

**Comment by daviddotzhang** [comment]
ci:retest

**Comment by daviddotzhang** [comment]
ci:retest

**Comment by moltam89** [comment]
Hi David,

I made progress on this issue, here is the current state:
https://github.com/moltam89/liferay-portal/commits/LPS-76111

**What I did so far per commits:**

**LPS-76111 Source formatting**:
No logical changes.

**LPS-76111 Use the original reference instead of creating it**:
I couldn't understand why it was necessary to generate the link again so I changed it to use the original reference from the content.

**LPS-76111 Change the beginPos for deleteTimestampParameters according to the new content**:
As far as I could see, the time stamp parameter wasn't removed when the document was in the trash, because of the newly added content. 
After my change the time stamp parameter will be removed completely when the document doesn't exist in Live, but I don't think that it will cause any problems.

**LPS-76111 Replace the same references at once** :
Before the fix, the same references were replaced at once, I think we could keep this.

**LPS-76111 Apply to legacy BaseTextExportImportContentProcessor**:
BaseTextExportImportContentProcessor is a legacy class containing the same logic, I copied everything to it.

**LPS-76111 Tests**:
I added more use cases.

I'll still need to revisit my changes, could you please share your oppinion about it?

Thanks,
Tamás

**Comment by daviddotzhang** [comment]
@moltam89 ,

I have conducted serval test cases, and also runned "gradlew testIntegration --tests *Test" under export-import-test folder. the fix works fine.  

It is OK for me.

**Comment by moltam89** [comment]
Hi David,

I forwarded it to https://github.com/matethurzo/liferay-portal/pull/1875.

Thanks,
Tamás

**Pull request closed without merging**
