### PR TITLE
LPS-70276 Property locale.prepend.friendly.url.style=2 affects available language order

### PR DESCRIPTION
**Pull request by rimisaadouwork**
Hi Tomcsi,

Could you please review this commit. This commit will be used in ee-6.2.x as well.
It is a major so please be very critical when you review this fix.
https://issues.liferay.com/browse/LPS-70276

Tanks!

### CODE REVIEW

**Comment by moltam89** [comment]
Hi @rimisaadouwork ,

could you please check what's wrong with the tests?
The exception coming from the **I18nServlet** seems related.

Thanks,
Tamás

**Comment by rimisaadouwork** [comment]
ci:retest

**Comment by rimisaadouwork** [comment]
ci:stop

**Comment by rimisaadouwork** [comment]
ci:retest

**Comment by rimisaadouwork** [comment]
Hi @moltam89,
I fixed the issue with the test. But I see other tests failing but those are not mine.

Thanks!

**Comment by moltam89** [comment]
Hi @rimisaadouwork ,

**shouldn't we check first whether the Site uses the default settings or not?**
I'm a bit scared about the API change in PortalImpl (and probably we won't really need the changes in I18nServlet and I18nFilter in this case), if we pass the groupId, but the Site uses the default language settings, I don't think we should change the logic.


**Also shouldn't we check if a LanguageCode is duplicated on Site level?**
Now it is checked at Company level, but if we try to use the Site settings, I think we should do the check on Site level.

Honestly this part of the portal is so fragile that I'm scared of every change.
**If it's a critical issue, I think we should involve the engineering team as soon as we can.**
cc @zsigmondrab
Properly reviewing this code from every aspect could take days for me, the new logic seems quite complicated in **I18nServlet** , I don't really know what's going on there.



THanks,
Tamás

**Pull request closed without merging**
