### PR TITLE
LPS-90347 Prevent archived setups from purging journalContentSearch

### PR DESCRIPTION
**Pull request by balazssk**
Hi @moltam89 ,
https://issues.liferay.com/browse/LPS-90347
Can you please review?

Thanks,

### CODE REVIEW

**Comment by balazssk** [comment]
Hi @moltam89 ,
Can you please look this through today, as we might need to forward this to Daniel Couso as well.

Thanks

**Comment by moltam89** [comment]
ci:test:relevant

**Comment by moltam89** [comment]
Hi @balazssk ,

I'll check this today.

Regards,
Tamás

**Comment by moltam89** [comment]
Hi @balazssk ,

I don't understand why the original condition was removed.
Could you please explain it?

Thanks,
Tamás

**Comment by balazssk** [comment]
Hi @moltam89 ,
The original condition was always returning true as all the archived settings were following up on an actual placed JournalContentPortlet, which would always have a plid set for the portletDataContext.

**Comment by balazssk** [comment]
Hi @moltam89 ,
Thanks for pointing out https://issues.liferay.com/browse/LPS-66533, I'll double check my modifications.

**Pull request closed without merging**
