### PR TITLE
[TECHNICAL-SUPPORT] LPS-83064

### PR DESCRIPTION
**Pull request by Alec-Shay**
Relevant tickets:

https://issues.liferay.com/browse/LPP-30548
https://issues.liferay.com/browse/LPS-83064

I'm sending this directly to you, Tamas, as we're trying to follow a new workflow for Staging issues here.

The code for determining the parentResourceClassName for imported KBArticles is incorrect because it relies on guessing based on existing classPK's (regardless of site). It's unlikely, but this can cause issues with imports when folders (or possibly articles) in other sites have the expected value, even though it should be remapped to a new value after the import.

I tried to remove some of the confusing logic with this, by leveraging the existing reference import method from `BaseStagedModelDataHandler`. I don't think this would cause problems -- but if there is some problem with this I didn't see, please let me know. Thank you!

### CODE REVIEW

**Comment by Alec-Shay** [comment]
ci:test

**Comment by Alec-Shay** [comment]
@moltam89 Apologies, I forgot that this should be closed for now due to the code freeze in master. I will take back the LPS for now and reopen this PR once that is changed.

**Comment by Alec-Shay** [comment]
@moltam89 Reopening as the release is finished and we are resuming sending pulls normally.

**Comment by moltam89** [comment]
Hi Alec,

I didn't have time to check this pr, I'm planning to do it on Monday.

Thanks,
Tamás

**Comment by Alec-Shay** [comment]
Hi @moltam89,

No worries, thanks for letting me know.

**Comment by moltam89** [comment]
Hi @Alec-Shay ,

I had a hard time to review this pr, as I'm not really familiar with the Knowledge Base portlet.
From general Staging point of view, I can't see any problems with this fix.

I think someone from the Knowledge Base team should review this pr as well, as it's quite application specific logic .
Could you please forward this pr to the Knowledge Base team? 

**Notes:**
- It might be a problem if a KB article references attachments only, as the new logic only sets the _parentResourceClassNameId_ if the type is REFERENCE_TYPE_PARENT.

- I think it's generally a good idea to  get rid of the unnecessary commits to help the reviewer. I'd merge the "SF" and "Fix error for root articles" commit to the first commit.

Thanks,
Tamás

**Comment by Alec-Shay** [comment]
Hi @moltam89,

Thanks for taking a look at this. I'll go ahead and get someone from the KB team to look at it as well.

In reference to your notes:

* I think you're right about the logic -- specifically if a root article has only a different type of reference (like an attachment), then the parentResourceClassNameId won't get set at all and that could be a problem. I suppose it should be the default assumption that it's in a folder, so that should not only be set if the referenceElement is null (I think I'll make that a new commit as it does require a bit of explanation).
* I am getting rid of the unnecessary commits now.

Thanks again!

**Comment by Alec-Shay** [comment]
Sent to: https://github.com/sergiogonzalez/liferay-portal/pull/4515

**Pull request closed without merging**
