### PR TITLE
[TECHNICAL-SUPPORT] LPS-88833

### PR DESCRIPTION
**Pull request by Alec-Shay**
**LPS**: https://issues.liferay.com/browse/LPS-88833

Notes from @diana-lin:

> **Problem**: When using the Copy as New import strategy for a LAR that contains a `JournalArticle` (Web Content) which references a `FileEntry` (Document), the `JournalArticle`'s corresponding `DDMStructure` and `FileEntry` are not able to be retrieved.  This causes there to be an incorrect reference between the imported Web Content and the Document that it links to.  This occurs for the following reasons:
> 
> 1. The `DDMStructure` is not retrievable from the method call [`article.getDDMStructure();`](https://github.com/joshuacords/liferay-portal/compare/master...diana-lin:LPS-88833?diff=split#diff-22369e9a475b7b8033e26579bde27bb6L576) because the structureKey being obtained from the LAR is out of date.
> 2. The `FileEntry` is not retrievable from the method call [`_dlAppService.getFileEntryByUuidAndGroupId(uuid, groupId);`](https://github.com/joshuacords/liferay-portal/compare/master...diana-lin:LPS-88833?diff=split#diff-18a6eb4090a1688a32fb3a2dd5faa15fL326) because the UUID and groupId that are being imported are out of date.
> 
> Note:  The structureKey for the `DDMStructure` and the UUID and groupId for the `FileEntry` are out of date because a new `DDMStructure` and `FileEntry` are created when using the Copy as New import strategy.
> 
> **Solution**:  Obtain the newly created `DDMStructure` and `FileEntry` that correspond to those which are being imported from the LAR.  This is done by making use of the StagedModel and PortletDataContext to obtain referenceElements according to an object's class.

Can you let us know what you think about this one when you get the chance? Thanks!

### CODE REVIEW

**Comment by Alec-Shay** [comment]
ci:test

**Comment by moltam89** [comment]
Hi @diana-lin , @Alec-Shay ,

I have a few questions about this fix.

**Do we need to separate the logic by the Data Strategy?**
It seems weird to me to have different logic when the Data Strategy is Mirror, can't we use the same logic for both cases?

About the first commit.
**Can't we use the newPrimaryKeysMap to obtain the correct structureKey like in [JournalArticleStagedModelDataHandler](https://github.com/liferay/liferay-portal/blob/master/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/internal/exportimport/data/handler/JournalArticleStagedModelDataHandler.java#L673-L679)**?

About the second commit.
**Have you tested the fix with other entities where the DDMFormValuesExportImportContentProcessor is used?**
Also, maybe a simpler solution could be if the LAR would contain the fileEntryId, so we could use the newPrimaryKeysMap again.
This is how the ImageImportDDMFormFieldValueTransformer works, though as far as I can see, in case of an Image field, the fileEntryId is stored, while for Document fields, the fileEntryId is missing.

Thanks,
Tamás

**Comment by diana-lin** [comment]
Hi @moltam89,

> **Do we need to separate the logic by the Data Strategy?**
It seems weird to me to have different logic when the Data Strategy is Mirror, can't we use the same logic for both cases?

Yes, technically the same logic could be used for both cases.  However when the Data Strategy is Mirror, we expect that the FileEntry or DDMStructure exists and thus is retrievable when using the corresponding `get...()` method.  The primary reasons that I chose to separate the two cases are:
1) Using the `get...()` method when the data strategy is Mirror provides an extra layer of validation that the FileEntry or DDMStructure does indeed exist as we expect it should (additionally it properly handles the `NoSuchFileEntryException` for FileEntry in the case that it doesn't exist).
2) It seems more efficient to retrieve the FileEntry or DDMStructure directly using a `get` method when it is available rather than through the `PortletDataContext` and `StagedModel`.

> About the first commit.
> **Can't we use the newPrimaryKeysMap to obtain the correct structureKey like in JournalArticleStagedModelDataHandler?**

Yes, the structureKey can be obtained from the newPrimaryKeysMap.  However, it is not a primary key so it cannot be used to obtain a DDMStructure -- the DDMStructureId is used for obtaining the structure instead.

> About the second commit.
> **Have you tested the fix with other entities where the DDMFormValuesExportImportContentProcessor is used?**

I've tried testing with other entities but have found that importing LAR files using the Copy as New data strategy is not behaving as expected in those cases, and so my scope of testing is limited to Web Content (`JournalArticle`).

In particular, the following unexpected behaviour occurs: 

- When importing LAR files containing Content that is linked to a Documents and Media file entry (e.g. Dynamic Data List, Knowledge Base, Message Board),  the file entry is not properly linked after using the Copy as New import data strategy.  In particular, the Documents and Media field that should contain the linked file entry is blank after it is imported when it should be properly populated.

> Also, maybe a simpler solution could be if the LAR would contain the fileEntryId, so we could use the newPrimaryKeysMap again.
> This is how the ImageImportDDMFormFieldValueTransformer works, though as far as I can see, in case of an Image field, the fileEntryId is stored, while for Document fields, the fileEntryId is missing.

Yes, I agree that a simpler solution could be to use the newPrimaryKeysMap to retrieve the fileEntryId.  The reason that I did not take this approach is because, as you pointed out, the fileEntryId is missing for Document fields.  **Is the storage of fileEntryId of Document fields something that should be changed/added?**  A concern that I have with taking this approach is that LAR files that were created prior to this fix would not contain the fileEntryId.

Please let me know if there is anything else that I can clarify.

**Comment by moltam89** [comment]
Hi @diana-lin ,

if there are problems with other entities, then I can't forward this pr, we need a solution which works properly in all cases.

> Is the storage of fileEntryId of Document fields something that should be changed/added?

Would it cause any problems if the fileEntryId would be stored as well?
Actually, this question should be asked from the DM or DDM teams.
If it's not possible to store the fileEntryId , the export/import process could be extended, to store it in the LAR.

Thanks,
Tamás

**Pull request closed without merging**
