### PR TITLE
LPS-70518 Referecing an edited article imported with resource importer makes Site Template import validation fail

### PR DESCRIPTION
**Pull request by rimisaadouwork**
Hi,

Could you please review this commit.

https://issues.liferay.com/browse/LPS-70518
https://github.com/moltam89/liferay-portal-ee/pull/17/commits/2c3bde7fed206584c948ffaed51cc7b9332991f0

Thanks!

### CODE REVIEW

**Comment by moltam89** [comment]
Hi @rimisaadouwork ,

did you manage to reproduce the issue in master?

Thanks,
Tamás

**Comment by rimisaadouwork** [comment]
Hi @moltam89 ,

No, I could not create a theme with global resources. Do you know how to do that for master?

Thanks!

**Comment by moltam89** [comment]
Hi @rimisaadouwork ,

I can see that there is a [documentation ](https://dev.liferay.com/develop/tutorials/-/knowledge_base/7-0/importing-resources-with-a-theme ) about it on the Developer Network, though I never tried it.

If it isn't straightforward enough, we can try to create some alternative reproduction steps as well.

If I understand it correctly, the already existing theme for 6.2 creates a JournalArticle with the default userId and a predefined articleId.
If we deploy it to another bundle, it will create a JournalArticle with the same articleId.

For master we could create such an environment with manual steps, e.g. with the following steps:

- Set up two bundles
- Create a JournalArticle in each bundle
- Change the JournalArticles userId to the defualt userId, and modify the articleId to the same value.

We can modify the articles via a groovy script, or we can modify the database directly.

This way we should have an environment where the issue is reproducible.

If we don't provide reproduction steps, then QA won't be able to test the issue, so it cannot be closed.
It is also possible to write an integration test, to cover this use case, but I think that wouldn't be easy.

Let me know if the proposed reproduction steps don't work for some reason.

Thanks,
Tamás

**Comment by moltam89** [comment]
Hi Rimi,

could you please update the LPS according to https://github.com/moltam89/liferay-portal-ee/pull/17#issuecomment-283928468?

I guess at step 6, we should export a Site, where e.g. a Web Content Display portlet is displaying the article from the Global scope.

BTW, don't we need the same logic in **doExportStagedModel** method, where we also use the preloaded flag?

Thanks,
Tamás

**Comment by moltam89** [comment]
Forwarded to https://github.com/liferay/com-liferay-journal/pull/306.

Thanks,
Tamás

**Pull request closed without merging**
