### PR TITLE
[TECHNICAL-SUPPORT] LPS-98088

### PR DESCRIPTION
**Pull request by Alec-Shay**
https://issues.liferay.com/browse/LPS-98088

Hello,

Here is a fix for properly skipping processing content in the content processor classes when the portlet should not be exported at all. Can you take a look at it for us and let us know your thoughts? Thanks!

Notes from @joshuacords:

> Resending after addressing test failures.
> 
> **Problem**: Changes from [LPS-79312](https://github.com/liferay/liferay-portal-ee/commit/aa08c6a8afb12f7515c5ba6d2c103e204b0e2b0e) uses PortletPreferences to export Blogs, WIki, Documents, and Message Boards - however it only references the individual checkboxes (the ones that can be seen after clicking "Change"). This approach didn't take into account the master checkboxes for the entire group.
> **Solution**: Take into account the master checkboxes for the entire group.
> 
> **Note**: Bookmarks is not part of master, but a similar change is necessary where LPS-79312 is backported and bookmarks exist.

### CODE REVIEW

**Comment by Alec-Shay** [comment]
ci:test

**Comment by moltam89** [comment]
Hi guys,

I've started the review, but I won't be able to finish it today.
I have 2 questions so far.

I can still see the bookmarks related modules in master, did we stop fixing bugs in bookmarks?

LPS-79312 wasn't backported to 7.0, LPS-86511 was created as a unique fix.
Have you considered shipping LPS-86511 to the customer instead? 

cc @joshuacords 

Thanks,
Tamás

**Comment by joshuacords** [comment]
Hello @moltam89,

I looked into LPS-86511, unfortunately that doesn't resolve LPP-31869 (which the hotfix for LPS-79312 does). I'll look into Bookmarks, I may have missed it in master.

**Comment by joshuacords** [comment]
Resent with bookmarks included here: https://github.com/moltam89/liferay-portal/pull/511

**Comment by joshuacords** [comment]
ci:close

**Comment by moltam89** [comment]
Hi @joshuacords ,

Okay, I thought it might be a better way to bring closer the customer code base to 7.0, but I don't really know the details, I'll concentrate on the fix for master.

Thanks,
Tamás

**Pull request closed without merging**
