### PR TITLE
LPS-131578 As an Instance Administrator, I want to be able to choose whether or not to publish content via display portlets

### PR DESCRIPTION
**Pull request by moltam89**

### CODE REVIEW

**Comment by moltam89** [comment]
ci:test:sf

**Comment by moltam89** [comment]
ci:test:relevant

**Comment by moltam89** [comment]
ci:test:stable

**Comment by moltam89** [comment]
ci:test:staging

**Comment by moltam89** [comment]
Hi @gaborlovasdotcom,

Do you have any ideas why ci:test:staging is failing?
It passes on my local machine.

Thanks

**Comment by JoyceWang08211** [comment]
Hi @moltam89,
For the two failures under ci:test:staging:
1. The failure of functional test **LocalFile.RemoteStaging#PublishCustomFieldDeletionviaRemoteStaging** is an intermittent bug which was reported in https://issues.liferay.com/browse/LPS-143838
2. The failure of integration test **com.liferay.staging.test.StagingDataPortletPreferencesTest**, I noticed this test passed on ci:test:relevant run with the same gitID. You can check this in [testray history ](https://testray.liferay.com/home/-/testray/cases/1590344977).

**Comment by JoyceWang08211** [comment]
ci:test:staging:nocompile

**Comment by JoyceWang08211** [comment]
Context: 
Run A: the second run of ci:test:staging
Run B: the first run of ci:test:staging

I compared the results between Run A and Run B, see details [here](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1641879922755&testrayRunIdA=1598397454&testrayRunIdB=1598118175). 

Only one integration test failed on both runs: [com.liferay.staging.test.StagingDataPortletPreferencesTest](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1598118175&testrayRunIdA=1598397454&testrayTeamId=1310700916&statusB=3).

@moltam89 you may need a deeper investigation about this failing integration test.

**Comment by moltam89** [comment]
Thanks @JoyceWang08211 for the analysis.

Could you please run "**gw testIntegration --tests StagingDataPortletPreferencesTest**" from **liferay-portal/modules/apps/staging/staging-test**?

If the tests passes in local machines, I'll forward this to Brian, as I don't really know how to fix errors on CI side.

**Comment by moltam89** [comment]
ci:test:relevant

**Comment by moltam89** [comment]
Rebeased and resent here:
https://github.com/moltam89/liferay-portal/pull/664

**Pull request closed without merging**
