### PR TITLE
LPS-68898

### PR DESCRIPTION
**Pull request by jonathanmccann**
Hey @moltam89,

This is the issue we were discussing on the forums concerning exporting embedded portlet's preferences. @holatuwol and I have put together this fix, so let me know what you think about it. There are three main parts to the fix:

1. Using portlet ID instead of root portlet ID since we should always be getting the actual portlet. This is necessary because the Web Content Display portlet is considered instanceable so getting the root portlet ID will be incorrect and the preferences won't be exported/imported correctly.
2. Using the group owner type when passing the group ID to the preferences instead of using the layout owner type with a group ID which causes a mismatch.
3. Rearranging how preferences are retrieved so that the embedded logic is used across the board. Without this change, the correct preferences for embedded portlets are not retrieved since it tries to fetch the layout's preferences instead of the group's.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by moltam89** [comment]
Hi @jonathanmccann, @holatuwol ,

I checked the changes related to PortletExportController and PortletImportController classes.
I understand that we need to handle instanceable portlets as well, but as far as I can see  the fix for[LPS-30387](https://issues.liferay.com/browse/LPS-30387) used rootPortletId on purpose, won't we break it?

About the other changes, I'm not sure if I'm the right person to review it, maybe we could find someone who is more familiar with the preferences handling.

Thanks,
Tamás

**Comment by jonathanmccann** [comment]
Hey @moltam89,

I ran the LayoutSetPrototypePropagationTest.testPortletPreferencesPropagationWithPreferencesUniquePerLayoutEnabled and it did fail.

The reason we changed it was that when importing the pages, we had no (feasible) way of determining whether or not a portlet is embedded because we no longer have access to the original layout. Do you have any ideas on how to get around that?

Thanks,
Jonathan

**Comment by moltam89** [comment]
Hi @jonathanmccann ,

I can't really have any specific advise, the fix for LPS-30387 was implemented quite long ago, I'm not familiar with it.
I guess we will need to understand the original logic first, so a new one can be created which solves the current issue without introducing any regressions.
If there is any specific question about LPS-30387, we can ask Daniel Kocsis who implemented it, he is always ready to help.

Tamás

**Comment by jonathanmccann** [comment]
Thanks Tamás. I'll keep working on it.

**Pull request closed without merging**
