### PR TITLE
LPS-98511 Wrong xpath selector in PortletDataContextImpl.getImportDataGroupElement() causing NPE

### PR DESCRIPTION
**Pull request by almonwork**

### CODE REVIEW

**Comment by almonwork** [comment]
Hi @moltam89 ,

I had some discussions about this with Daniel Kocsis. My previous solution [LPS-97705](https://issues.liferay.com/browse/LPS-97705) caused [LPS-98333](https://issues.liferay.com/browse/LPS-98333)

Based on my debugging sessions, I would say the test is wrong. Tests create an importDataRootElement like <root><DLFileEntry>...</DLFileEntry></root> In such cases, ".//" works, altough I don't really understand why. But, while actually importing a lar file, importDataRootElement looks like <DLFileEntry>...</DLFileEntry>. In this case, "//" is the appropriate selector. I am unsure about changing the test, as there might be other use cases.

The solution in this PR considers both cases. The tests do not fail and the import process is successful.

Regards

**Comment by almonwork** [comment]
ci:test:relevant

**Comment by moltam89** [comment]
Hi @almonwork ,

I don't really understand this change.

According to the [XPath spec](https://www.w3.org/TR/1999/REC-xpath-19991116/), it's okay to use ".//" 

> //para selects all the para descendants of the document root and thus selects all para elements in the same document as the context node

> .//para selects the para element descendants of the context node

Is there any use cases when it is needed to search from the root element?
It would be nice to have reproduction steps, otherwise I don't know what is the issue we're trying to resolve.

Thanks,
Tamás

**Comment by almonwork** [comment]
Hi @moltam89 ,

This PR is in the context of PTR-985 and PTR-1003 (see also LPP-34186). The customer is trying to import a large .lar (reproduction steps [here](https://issues.liferay.com/browse/PTR-985?focusedCommentId=1890241&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1890241), and they found several issues.

I edited my first comment (some characters were not escaped).

I am doing a few extra checks about .// and // .

Regards
  Alberto

**Comment by almonwork** [comment]
Hi @moltam89 ,

I have been doing some extra checks, and I am a bit confused.

If you run the following script

```import com.liferay.portal.kernel.xml.SAXReaderUtil;
import com.liferay.petra.xml.Dom4jUtil;
import com.liferay.portal.kernel.util.HtmlUtil;

xmlContent = '''
<root>
 <missing-references></missing-references>
 <DLFileEntry>
  <staged-model group-id="41552" uuid="87eadb24-9f6b-d001-136a-eb0279d926d2" fileVersionUuid="0fa6e71a-789a-b09f-2119-e4dad81f6408" version="1.0" bin-path="/group/41552/com.liferay.document.library.kernel.model.DLFileEntry/41569/1.0" path="/group/41552/com.liferay.document.library.kernel.model.DLFileEntry/41569.xml" user-uuid="b71563a1-d00a-7d72-6cc2-9397fddefb58" asset-entry-priority="0.0">
   <references>
    <reference class-name="com.liferay.document.library.kernel.model.DLFolder" class-pk="41565" group-id="41552" group-key="8vHLe0ah" live-group-id="41552" type="parent" uuid="db183933-43df-3d95-36f5-fdbc5bdb7f69" company-id="20097" missing="false"></reference>
    <reference class-name="com.liferay.document.library.kernel.model.DLFileEntryType" class-pk="41560" group-id="41552" group-key="8vHLe0ah" live-group-id="41552" type="strong" uuid="0198330f-7661-bdde-afde-d138c48d9e0a" company-id="20097" file-entry-type-key="41559" preloaded="false" missing="false"></reference>
    <reference class-name="com.liferay.asset.kernel.model.AssetCategory" class-pk="41588" group-id="41552" group-key="8vHLe0ah" live-group-id="41552" type="weak" uuid="2fd4d945-1b37-c9ff-7962-56ee0dfa702f" company-id="20097" missing="false"></reference>
    <reference class-name="com.liferay.asset.kernel.model.AssetTag" class-pk="41590" group-id="41552" group-key="8vHLe0ah" live-group-id="41552" type="weak" uuid="243ccca0-010f-0aed-baa0-fb50621967cf" company-id="20097" missing="false"></reference>
   </references>
   <structure-fields ddm-form-values-path="/group/41552/com.liferay.dynamic.data.mapping.model.DDMStructure/41555/41572" structureUuid="ebbf1094-c512-4022-5f3e-26904d883f1d"></structure-fields>
  </staged-model>
 </DLFileEntry>
 <DLFolder>
  <staged-model group-id="41552" uuid="db183933-43df-3d95-36f5-fdbc5bdb7f69" defaultFileEntryTypeUuid="" path="/group/41552/com.liferay.document.library.kernel.model.DLFolder/41565.xml" user-uuid="b71563a1-d00a-7d72-6cc2-9397fddefb58" asset-entry-priority="0.0"></staged-model>
 </DLFolder>
</root>'''

document = SAXReaderUtil.read(xmlContent);

out.println(HtmlUtil.escape(document.formattedString(" ", true)))

out.println(HtmlUtil.escape(document.selectSingleNode(".//DLFileEntry").formattedString(" ", true)))

out.println(HtmlUtil.escape(document.selectSingleNode(".//DLFileEntry").formattedString(" ", true)))```

you will obtain the same output using // and .//. OK

However, if you take a look to [this PR](https://github.com/brianchandotcom/liferay-portal/pull/75824/files), you will see it only changes // to .//, but it generates regressions (see [LPS-98333](https://issues.liferay.com/browse/LPS-98333) . So, there is something else in the import code that has not been captured in the script above. 

What I can say for sure is that changing // to .// allows the .lar file to be imported, falling otherwise.

Can you see any difference?

Regards
  Alberto

**Comment by almonwork** [comment]
Script edited.

**Comment by moltam89** [comment]
Hi Alberto,

I can't see the difference.

I've applied the first solution and then debugged the failing FolderStagedModelDataHandlerTest, but I couldn't figure it out why did it fail.

I'm afraid it's not safe to merge this change, without knowing the exact reasons why it is needed.

Best,
Tamás

**Comment by almonwork** [comment]
Hi Tamás,

I understand your concers. And I share them.

However, keeping current code would prevent lars from being imported, so the situation is not better.

The change is safe, as if './/' returns something, the previous behaviour is preserved. Only if it returns null, '//' is applied.

Another discussion is wether we should change de test or not, as \<root\> doesn't seem to be part of the data structure in a real import case.

Regards 
  Alberto

**Comment by almonwork** [comment]
Hi @moltam89 ,

Did you have the chance to review my previous comment? 

This customer is active again and we need to provide an answer.

Regards

**Comment by moltam89** [comment]
Hi @almonwork ,

I wouldn't like to forward this fix without clean reproduction steps (in master).

Without steps I can't be sure that we're not just hiding another problem and the fix is the correct one.

Thanks,
Tamás

**Comment by almonwork** [comment]
Hi @moltam89 ,

I understand your concerns. Can you help me finding a set of clean reproduction steps?

Regards
  Alberto

**Comment by moltam89** [comment]
Sorry @almonwork ,

I don't have the bandwidth for this right now.

@zsigmondrab could you please help with prioritizing this task?

**Pull request closed without merging**
