### PR TITLE
[TECHNICAL SUPPORT] LPS-89294

### PR DESCRIPTION
**Pull request by Preston-Crary**
@knchau Everything after e28c17a is code cleanup and causes a minor semantic version change, if you need to ignore anything after that part for backport / patch that's fine.

CC @shuyangzhou

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:backend-hypersonic

**Comment by moltam89** [comment]
ci:test

**Comment by knchau** [comment]
Hi @moltam89,

Do you have an ETA when this pr can be reviewed?

Thank you!

**Comment by moltam89** [comment]
Hi @knchau ,

Sorry for the delay. I'll check this PR next week.

Thanks,
Tamás

**Comment by moltam89** [comment]
Sorry, I have to postpone this PR again for the next week.

**Comment by moltam89** [comment]
Hi guys,

I have a question about the changes which seem refactoring to me. Basically "Everything after e28c17a".
Is there a specific reason which triggered these changes?

I'm asking because staging is in maintenance mode, I think it would be better not to change the API.

Thanks,
Tamás

**Comment by Preston-Crary** [comment]
Goal of those changes is just to move staging code to the staging service instead of having it in the group service.  This should make maintaining staging code easier in the long run because many different services use the group service, few use the staging service directly.

**Comment by knchau** [comment]
Hi @moltam89,

Do you have any updates for this PR?

Thank you!

**Comment by moltam89** [comment]
Hi guys,

I don't think that it's a good idea to merge the not necessary API changes in a bugfix ticket.
It could make extra work for support.

As Staging is in maintenance mode, I'm not sure if API changes should be introduced at all.
I'm not against it, if the benefits are greater than the extra work we cause for support, but it would be nice to separate the changes in an other ticket.

Thanks,
Tamás

**Comment by Preston-Crary** [comment]
That's fine, update the pull.

**Comment by knchau** [comment]
Hi @moltam89,

Since the pull has been updated, can you take a look at this again?

Thank you!

**Comment by moltam89** [comment]
Hi guys,

Before the fix, there was a small icon next to the "Remote Live" buttons (on the control panel and on the widget pages) explaining that the Remote Live server is down.
After applying the fix, these info messages are gone. 

Could you please check if this works for you?

Thanks,
Tamás

**Comment by knchau** [comment]
Updated the pr here: https://github.com/moltam89/liferay-portal/pull/551

**Pull request closed without merging**
