### PR TITLE
LPS-115709

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@moltam89 a few things:

- `deleteBackgroundTask`: not sure about this one: https://github.com/liferay/liferay-portal/blob/master/modules/apps/staging/staging-configuration-web/src/main/resources/META-INF/resources/staging_configuration_exceptions.jspf#L34

- `deleteBackgroundTasks`: we have two classes that use `deleteBackgroundTasks`. For those it doesn't match the class name and it seems the classes are pretty much identical, except for the value of `javax.portlet.name`. Can you take care of those:

https://github.com/liferay/liferay-portal/blob/master/modules/apps/export-import/export-import-web/src/main/java/com/liferay/exportimport/web/internal/portlet/action/DeleteLayoutExportBackgroundTaskMVCActionCommand.java#L39
and
https://github.com/liferay/liferay-portal/blob/master/modules/apps/export-import/export-import-web/src/main/java/com/liferay/exportimport/web/internal/portlet/action/DeleteLayoutImportBackgroundTaskMVCActionCommand.java#L39

- `publishLayouts`, please carefully review https://github.com/moltam89/liferay-portal/pull/559/commits/f048e4e53b12c1bf24185b8f89aaf0bacc42afd5

**Comment by hhuijser** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
ci:test:sf

**Comment by moltam89** [comment]
Hi @hhuijser ,

It looks like to me that some of the mvc.command.names were identical on purpose.
The _staging-taglib_ contains actionURLs which are used from the _export-import-web_ and the _staging-processes-web_  modules as well.

Can we make an exception and keep the original names, or do we need another solution?

Thanks,
Tamas

**Comment by hhuijser** [comment]
@moltam89 I am okay making an exception for these.
Do you mind at least renaming, so we use format `publish_layouts` instead of `publishLayouts`?

Can you take care of this?

**Comment by moltam89** [comment]
Hi @hhuijser ,

I've realised that it's possible to determine the mvc command name from the portlet name in the taglib, I went for this solution instead. This way there is no need to create an exception.

I found one place where the old command name was used, otherwise everything looks good to me.

I've sent you a pull request:
https://github.com/hhuijser/liferay-portal/pull/5094

Thanks,
Tamas

**Pull request closed without merging**
