### PR TITLE
[TECHNICAL-SUPPORT] LPS-99342

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by moltam89** [comment]
Hi @jonathanmccann ,

I'm having trouble with reproducing the issue following the steps from LPS-99342, I can't find the time zone selector in current master.

Am I missing something?

Thanks,
Tamás

**Comment by jonathanmccann** [comment]
Hi @moltam89,

The changes in LPS-93315 added the backend for allowing a time zone to be utilized as well as some functional changes to display it in the UI. The functional part of LPS-93315 was reverted under LPS-99342. The changes on this pull request bring back the functional changes and fix an issue with scheduling the job.

In short, on Master there is no time zone selector.

Please let me know if you have any other questions.

Jonathan

**Comment by moltam89** [comment]
Hi @jonathanmccann ,

Sorry for the late response.

I think the fix is good.

I read [PTR-1133](https://issues.liferay.com/browse/PTR-1133) and I'm confused a little bit, because according to the PTR it's not possible to schedule a publication to the past. However, I tested this in 7.1.x (just to make sure LPS-93315 doesn't affect it) and I could schedule an event for yesterday. Also I can do this after the current fix, which is I think expected, as we didn't want to introduce behavior change  in this area.
Am I missing something or is the communication a bit misleading on the PTR?

**Note:**
Probably I found a problem with the original solution, if I'm not very much mistaken selecting a time zone for Publish Templates with Remote Staging won't work, as we don't persist the time zone. It should be an easy fix to add [this](https://github.com/liferay/liferay-portal/commit/cd1cfcddf4f6311420cd61ea0d23a2238c5329cc) logic for remote staging as well, I'm planning to add an extra commit before I forward the PR.

Thanks,
Tamás

**Comment by jonathanmccann** [comment]
You are correct. Previously you could schedule publishes in the past and with the current solution that is still possible.

I'm not sure why the opposite was stated on the PTR but it is incorrect.

**Comment by moltam89** [comment]
Thanks for the clarification.

https://github.com/brianchandotcom/liferay-portal/pull/81034

**Pull request closed without merging**
