### PR TITLE
LPS-103991 Remove change tracking logic from staging

### PR DESCRIPTION
**Pull request by stsquared99**
Hi @moltam89, could you please review these changes for me? Thanks!

cc @Preston-Crary

### CODE REVIEW

**Comment by stsquared99** [comment]
ci:test

**Comment by stsquared99** [comment]
ci:test

**Comment by moltam89** [comment]
Hi @stsquared99,

Sorry for the late response, I had to take yesterday off unexpectedly.

It surprised me a little bit that removing from the API didn't trigger version changes.
I found that LPS-103157 removed some deprecated methods and that's why we jumped a major version. 
As staging is in maintenance mode, I'm not sure if this was intentional.

I'd like to hold this PR until the situation is cleared.
Is there a deadline for this current ticket which I should consider?

Thanks,
Tamás

**Comment by stsquared99** [comment]
No rush, thanks!

**Comment by stsquared99** [comment]
Hi @moltam89, just wanted to check in to see where we stand? Thanks!

**Comment by moltam89** [comment]
Hi @stsquared99 ,

After discussing LPS-103157 with Zsigmond, we decided that it's okay that the depcrecated methods were removed and we jumnped a major version.

I forwarded the PR to Brian: https://github.com/brianchandotcom/liferay-portal/pull/81480.

Sorry for keeping this unnecessarily in my queue for a while.

Thanks,
Tamás

**Pull request closed without merging**
