### PR TITLE
[TECHNICAL-SUPPORT] LPS-88014 Return early if the group is deleted to avoid an NPE testing if the group is staged or not

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
ci:test:staging

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by moltam89** [comment]
Forwarded to https://github.com/matethurzo/liferay-portal/pull/2306.

Thanks!

**Pull request closed without merging**
