### PR TITLE
[TS] LPS-98473

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-98473

Original PR: https://github.com/moltam89/liferay-portal/pull/522

Please let me know if you have any questions.

CC @lipusz

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Test failure is unrelated, see https://github.com/drewbrokke/liferay-portal/pull/861#issuecomment-520061441 for identical error.

**Comment by moltam89** [comment]
Hi @ChrisKian ,

This looks good to me, as it is journal specific, I've forwarded the PR to https://github.com/ealonso/liferay-portal/pull/2503.

Thanks,
Tamás

**Pull request closed without merging**
