### PR TITLE
LPS-121918 Migrate v2 usages in staging/staging-processes-web

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @moltam89,

Attached is an update for http://issues.liferay.com/browse/LPS-121918.

**Test Plan:**

1. Login to Liferay
2. Click on the **Product Menu**
3. Click on **Publishing** -> **Staging**
4. Enable **Local Live** staging configuration and select options and click **Save** 
staging

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:test:sf

**Comment by jonmak08** [comment]
ci:test:relevant

**Review by julien — APPROVED** [review]

**Review by markocikos — APPROVED** [review]
LGTM!

**Comment by moltam89** [comment]
ci:forward

**Pull request closed without merging**
