### PR TITLE
LPS-131578 As an Instance Administrator, I want to be able to choose whether or not to publish content via display portlets	

### PR DESCRIPTION
**Pull request by moltam89**
Hi @liferay-echo, @liferay-forms, @liferay-lima,

The goal of this story is to make the staging process faster by not publishing content when it is unnecessary.

**DDLDisplay, DDMForm, JournalContent** and **WikiDisplay** were modified, therefore I think you should double check this.

Users probably won't notice any difference, as usually the content is already available in Live, or it will be published via the admin portlets.

Let me know if you have any questions.

Best,
Tamas

### CODE REVIEW

**Comment by moltam89** [comment]
ci:test:sf

**Comment by moltam89** [comment]
ci:test:relevant

**Comment by moltam89** [comment]
ci:test:stable

**Comment by moltam89** [comment]
ci:test:staging

**Comment by natocesarrego** [comment]
Hey @moltam89,

Sorry for the delay to do the review, I didn't check the @liferay-forms notifications. :grin: I'll do the review on Monday morning.

Thanks!

**Comment by adolfopa** [comment]
@moltam89 If I understood the changes correctly, this will prevent display portlets from triggering a full export/import, as new/updated content will be exported anyway by the admin side; so, if the portlet configuration changes, but no content is modified or added, we save some space/time. Is that right?

If that's the case, I'm ok with the changes.

**Comment by natocesarrego** [comment]
Hey @moltam89, in regards to DDL and Forms, feel free to move on with this pull. :slightly_smiling_face: 

Thanks.

**Comment by lfbesada** [comment]
Hi @moltam89 sorry for the delay, in regards to Journals, we are ok with the changes.
Have a nice New Year!

**Comment by moltam89** [comment]
Thanks everyone,

The rebeased version of this pull request will be forwarded to Brian, once all the tests pass:
https://github.com/moltam89/liferay-portal/pull/664

Best,
Tamas

**Pull request closed without merging**
