### PR TITLE
LPS-67444 When prepending the locale to the URL the site default should also be checked

### PR DESCRIPTION
**Pull request by hudakl**
Hi,

Please find my solution suggestion for the LPS-67444.
Could you please review my changes?

Thank you,
Laci

### CODE REVIEW

**Comment by hudakl** [comment]
ci:retest

**Comment by hudakl** [comment]
ci:retest

**Comment by hudakl** [comment]
ci:retest

**Comment by moltam89** [comment]
I've forwarded it to Giros, who recently worked on similar issues:
https://github.com/giros/liferay-portal/pull/42

**Pull request closed without merging**
