### PR TITLE
[TECHNICAL-SUPPORT] LPS-100082

### PR DESCRIPTION
**Pull request by jonathanmccann**
Hey @moltam89,

This pull is coming from @ChrisKian but he is on PTO for the next couple of months so I'll be handling the issue. If you have any questions or concerns I'll do my best to answer them but my background on the issue is limited.

Thanks.

### CODE REVIEW

**Comment by moltam89** [comment]
Hi Jonathan,

I don't think that I'm the right person to review this, checking the code really quickly I can see application specific changes only.

Could you please forward this to someone from the responsible teams?

Thanks,
Tamás

**Comment by jonathanmccann** [comment]
@moltam89 Definitely. I sent it through you first since it is a continuation of LPS-98473. If you're fine with the changes to Staging I can let the next reviewer know so that they don't ask me to route it through you.

**Comment by moltam89** [comment]
I don't see any staging core related changes. Do I miss something?

> If you're fine with the changes to Staging

If you mean the changes in JournalArticleStagedModelDataHandler, that's also app specific, so the journal team should decide.

**Comment by jonathanmccann** [comment]
Ah, apologies, I thought the model data handler was still part of staging. I'll forward this along, sorry about that.

**Comment by jonathanmccann** [comment]
https://github.com/ealonso/liferay-portal/pull/2524

**Comment by moltam89** [comment]
No problem, thanks!

**Pull request closed without merging**
