### PR TITLE
[TECHNICAL-SUPPORT] LPS-94690

### PR DESCRIPTION
**Pull request by Alec-Shay**
https://issues.liferay.com/browse/LPS-94690

/cc @danielkocsis

Hello @moltam89,

Here are the latest revisions to the fix for LPS-94690, taking the comments on https://github.com/moltam89/liferay-portal/pull/502 into account.

The latest notes from @knchau:

> Previous pr: https://github.com/moltam89/liferay-portal/pull/502
> Changes due to this https://github.com/moltam89/liferay-portal/pull/502#issuecomment-504002295
> 
> The issue is when the site is staging. At every page load of the Control Panel, the local server would send a request to the remote server. This can cause the site to hang because the request is sent in [SiteAdministrationPanelCategroyDisplayContext.getLiveGroupURL](https://github.com/SamZiemer/liferay-portal/compare/master...knchau:LPS-94690_1?expand=1#diff-2db79331dcd02f15d22749213538877fL46). The timeout can take 30 seconds.
> 
> My changes move the logic to the backend in a thread using the quartz scheduler. The quartz scheduler monitors the remote server's connection and updates the remote display URL. The listener would periodically ping the remote server and update its remote URL every hour. It initially caches the remote URL when remote staging is enabled -- https://github.com/SamZiemer/liferay-portal/commit/57f4925b957ad34854bb9497d824c927c203d79f. The remote URL value is cached in the group's type settings. 
> 
> https://github.com/SamZiemer/liferay-portal/commit/d8c88e4d967963a15d0f01f274a27111c95c52e8 -- It dynamically fetches all groups, then checks for those that are remotely staging and updates their remote display URL with GroupServiceHttp.getGroupDisplayURL that is in Staging.getRemoteSiteURL. It updates the group's type settings. It is not only updating the remote URL, but also monitoring the connection because it's pinging the server (in the backend).
> 
> The remote URL for the 'Remote Site' button on the Control Panel was originally updated by pinging the remote server, which can cause the site to hang because it was called on the jsp. https://github.com/SamZiemer/liferay-portal/commit/f4bde57eadb9e6785933bfe1ccba47e9987f2f35 changes it to fetch the remote URL from the group's type settings.

### CODE REVIEW

**Comment by Alec-Shay** [comment]
ci:test

**Comment by danielkocsis** [comment]
Hi @Alec-Shay,

@moltam89 and me went through the changes but found a few big issues in a very short amount of time. My request would be, to please communicate any time you run into an issue and do not make assumptions or decisions on your own, otherwise the round time is just getting longer and longer as we need to review the final solution, send it back, etc... 

Right now the issue we found (so far):
 - SiteAdministrationPanelCategoryDisplayContext.getLiveGroupURL() considered both local and remote staging, but the new solution doesn't
 - The scheduled task can't check both private and public layout sets for groups, but assumes only one of those exist
 - the user it chose for group checking probably wrong
 - it should use ActionableDynamicQuery instead of an unlimited query to get the groups


Also you opened a PTR (https://issues.liferay.com/browse/PTR-1005) what is probably not needed at all if this problem can be fixed, since the log won't be polluted with remote errors, only the scheduled task will throw it.

Please consider those question and ask for help if needed and resend the solution!

thanks,
Daniel

**Comment by knchau** [comment]
Hi @danielkocsis and @moltam89,

I reviewed the issues you guys have found and made the changes [here](https://github.com/knchau/liferay-portal/tree/LPS-94690_2). 

The current issue I am running into is choosing user for group. Do you have any suggestions for fetching the current user from the scheduler quartz? 

Thank you!

**Comment by danielkocsis** [comment]
hi @knchau ,

I would recommend to talk with security team regarding what user a system task like this should use when it needs to call an API what requires a user. Since this task is not running in the name of any real user, but more like a special system job, it can be the company default user, but security guys must be able to answer this better.

thanks,
Daniel

**Comment by knchau** [comment]
@danielkocsis, I see I'll contact them thanks!

**Comment by knchau** [comment]
Hi @danielkocsis and @moltam89, 

Security engineer notes an issue that might occur with using the company default user is when the site page is private, they might not be able to access it. 

He suggested another approach, so we can avoid selecting a user since the scheduler is not owned by any user. Instead of monitoring the remote site in scheduler quartz, we can monitor it in SiteAdministrationPanelCategory.getLiveGroupURL. The typeSettingProperties will be similarly cached as it is now but in liveGroupURL(), along with caching an additional last-updated-time property. The last-updated-time property is cached initially when the Control Panel is navigated, and when the last-updated-time is still relevant, we will provide the cached remote URL. This will have the browser ping within a configurable expiration interval. 

Please let me know your thoughts on this suggested approach.
/cc @zsoltbalogh

**Pull request closed without merging**
