### PR TITLE
[TECHNICAL-SUPPORT] LPS-89294

### PR DESCRIPTION
**Pull request by Alec-Shay**
/cc @gregory-bretall, @zsoltbalogh

Relevant tickets:

https://issues.liferay.com/browse/LPP-32794
https://issues.liferay.com/browse/LPS-89294

Re-sent from https://github.com/moltam89/liferay-portal/pull/482

Notes from @knchau:

> Incorporated suggested changes from previous pull https://github.com/moltam89/liferay-portal/pull/482
> 
> https://issues.liferay.com/browse/LPS-89294
> 
> Notes from previous pull:
> 
> > The issue was that the log error was being thrown on the console. I swallowed the log error if it was a ConnectException and displayed a UI error instead. I had to throw a RemoteExportException to display the proper banner by validating if the remote server is still live. If the connection is severed, it would throw a RemoteExportException for each tab and add a session error. I had to add session error for resourceRequest and renderRequest because the processes tab's view.jsp is called multiple times. renderRequest being used for the first call and resourceRequest for the calls thereafter. Scheduled tab's view.jsp includes the error file because processes tab handles the error message in its liferay-staging tag. The UI between the banner displays are different between the tabs because the processes tab has a management toolbar that has a margin-bottom which provides the gap between the toolbar and the banner whereas the scheduled tab only has the navigation toolbar which does not have any margins so there is no gap between that toolbar and the banner. The banners do not have any particular unique traits to provide a quick fix, so this is determined to be a separate issue.
> 
> And additionally:
> 
> > The fix was to throw an exception when switching between tabs, resulting in a UI display that there is no connection to the remote server. The error log is swallowed from the change to the service_http template.

### CODE REVIEW

**Comment by Alec-Shay** [comment]
ci:test

**Comment by moltam89** [comment]
Hi guys,

I found two problems while testing the fix.

Using **Local Staging** a NullPointerException is thrown when I navigate to the Processes or Scheduled tabs.

I enabled **Remote Staging** using two machines, then shut down the Live bundle.
The Processes/Scheduled tab loads very slowly. With the fix it took about 15 seconds longer to me.

Could you please check these issues?

Thanks,
Tamás

**Comment by zsoltbalogh** [comment]
@moltam89 is correct, in some cases this error message will make https://issues.liferay.com/browse/LPS-92464 worse.

I'll discuss with Máté how to solve this problem and will get back to you. Until then, please only work on the NPE with remote staging. 

Thank you, @moltam89 for catching it!

**Comment by knchau** [comment]
@zsoltbalogh, would you like me to push my resolve for the NPE with remote staging first or should I wait and push it along with the solution Máté and you come up with?

**Comment by zsoltbalogh** [comment]
Please wait, should have a solution today. Thank you for checking!

**Comment by knchau** [comment]
Hi @zsoltbalogh, just checking in if there's any progress? Thanks!

**Comment by zsoltbalogh** [comment]
@knchau , please follow the tickets for status updates (e.g. PTR-791), thank you!

**Comment by moltam89** [comment]
For future reference:

This issue has been reorganized and separated into LPS-89294 and LPS-94690.
https://github.com/danielkocsis/liferay-portal/pull/822

**Pull request closed without merging**
