### PR TITLE
LPS-76111 Publishing will fail if the linked document is in the Recycle Bin

### PR DESCRIPTION
**Pull request by daviddotzhang**

### CODE REVIEW

**Comment by moltam89** [comment]
ci:retest

**Comment by daviddotzhang** [comment]
@moltam89  May I know How is the review going?

**Comment by moltam89** [comment]
Hi @daviddotzhang ,

sorry for the delay, string manipulations like this are not straightforward, I'm having difficulties to read and understand the code properly.

I found another use case which seems to break the new logic:
1. Embed an image which is in the trash and doesn't exist in Live.
2. Embed other images
3. Embed the image again from step 1

In this case the images embedded at step 2 are not replaced correctly during the import, as far as I can see, while the first image URL is processed, the other URLs are modified also.

Could you please take a look at?

Thanks,
Tamás

**Comment by daviddotzhang** [comment]
@moltam89 got it.
thanks, I am able to reproduce the issue, and I will reconstruct the code.

**Pull request closed without merging**
