### PR TITLE
[TECHNICAL-SUPPORT] LPS-91233

### PR DESCRIPTION
**Pull request by Alec-Shay**
Relevant tickets:

https://issues.liferay.com/browse/LPP-32941 (partly related)
https://issues.liferay.com/browse/LPS-91233

When publishing content, there are various types of content validation that are performed, each of which may cause the publication to fail due to invalid references. Currently, we have an option in place to allow for disabling (some) layout references, although we do not have this for other types of validation that may occur.

This fix is simply adding two more such options, and making it possible to disable all of the reference validation from the `DefaultTextExportImportContentProcessor` call. This should help simplify workflow for users who do not necessarily want to maintain these references, as well as provide a bit more consistency for these options.

Note that language key translations still need to be generated for the new language keys. Additionally, I added the new keys following the pattern of the existing `validate-layout-references-help` key, although I added a commit to fix what seems like a grammatical error to me; if that is too much of a hassle to regenerate the new translations for that, though, it seems like a minor thing so maybe that doesn't need to be included necessarily.

### CODE REVIEW

**Comment by Alec-Shay** [comment]
Hi @moltam89,

Do you think you could take a look at this for us and let us know your thoughts on this? In this case it is a Story ticket, because it would be a stretch to call it a "bug," but it is something we need to push forward on our end (and we will also need to push to backport, as well) because it is complicating some use cases for clients.

Please let us know of any concerns or questions you may have about this; we've discussed this a fair bit on our end but I recognize this is a rather unusual way of moving forward. Thanks in advance.

**Comment by Alec-Shay** [comment]
ci:test

**Comment by moltam89** [comment]
Hi Alec,

Thank you, for the the detailed explanation.
I think this is the right direction and we should backport the fix as well.
I had a brief discussion with Máté and he agreed. 

About the language keys, should I generate them?
Sorry, I'm not familiar with the current workflow.

Also, I have to admit that I haven't really worked with configuration related issues, so I'm a bit lost here.
I see that that in the [LayoutReferencesExportImportContentProcessor ](https://github.com/liferay/liferay-portal/blob/master/modules/apps/export-import/export-import-service/src/main/java/com/liferay/exportimport/internal/content/processor/LayoutReferencesExportImportContentProcessor.java#L102) class, the exportImportServiceConfiguration is created in the activate method, while in the fix simply the @ Reference annotation is used.
Do you know the pros/cons between these two ways?
I'll need to read on the topic a little bit, it would be really helpful if you could point me to the right direction.

Thanks,
Tamás

**Comment by Alec-Shay** [comment]
Hi @moltam89,

Thanks for getting back to me on this. I'm glad we all seem to be in agreement on the direction of the fix.

As for the translations -- if you are able to do it, we would appreciate it. I don't know whether it's supposed to be up to anyone particular to generate them (I presume usually whoever is implementing it), but as far as I know, neither myself nor the normal reviewer(s) in our office seem to be able to, so we often leave it up to whoever can do it in review.

As for using the @ Reference annotation for the configuration, I'm really not sure what advantages there are; I did check again, though, and realized that for other *ServiceConfiguration classes, they seem to always be using ConfigurationProviderUtil (I found only one example of a ServiceConfiguration that initialized it the same way in [MediaWikiImporter](https://github.com/liferay/liferay-portal/blob/master/modules/apps/wiki/wiki-web/src/main/java/com/liferay/wiki/web/internal/importer/MediaWikiImporter.java#L806), though it was made that way at the same time as all of the other @ References with no explanation for the ServiceConfiguration specifically, so I can't be sure if that part was intentional). So I guess it would probably be best to stay in line with the current pattern and use that instead. I had been simply going off of what I thought to be generally our preferred strategy for initializing references with the annotation with DXP, though that wasn't thinking about it too much.

**Comment by moltam89** [comment]
Hi Alec,

I asked Máté about the language keys, we can simply run the buildLang task from the staging-lang module to generate the translations.

I found these articles which suggest to use the ConfigurationProvider in case of scoped configurations.
[Scoping configurations](https://dev.liferay.com/en/develop/tutorials/-/knowledge_base/7-1/scoping-configurations)
[Reading configuration values from a configuration provider](https://dev.liferay.com/en/develop/tutorials/-/knowledge_base/7-1/reading-configuration-values-from-a-configuration-provider).
Therefore I agree that we should use the ConfigurationProviderUtil.
Could you please extend the fix?

Thanks,
Tamás

**Comment by Alec-Shay** [comment]
Hi Tamás,

I'm going ahead and sending you a new pull, following the pattern outlined by the documentation you found (thanks for finding that, by the way): https://github.com/moltam89/liferay-portal/pull/480

I still have a concern about the language keys, but I'll add a comment about that on the new pull

**Pull request closed without merging**
