### PR TITLE
[TECHNICAL REQUEST] LPS-64886 Asset Publisher does not allow filtering for Basic Document…

### PR DESCRIPTION
**Pull request by peterborkuti**
Hi,

Please, review it. The LPP was verified by you so you may be familiar with the issue.

Thank you in advance
Péter

### CODE REVIEW

**Comment by moltam89** [comment]
Hi Péter,

the changes in the jsp file seems a bit complicated to me.

I think the 
 `if (defaultClassTypeId > 0) {` 
check in **getClassTypeIds** method (AssetPublisherUtil ) should be fixed as well.
This way the changes in the jsp file could be unnecessary, as the **assetSelectedClassTypeIds** array will contain the proper value.

Could you please check it?

Thanks,
Tamás

**Comment by peterborkuti** [comment]
Hi Tamás, thanks, it worked. I refreshed my pull. I am creating an SDH.

**Comment by moltam89** [comment]
Hi Péter, 

currently I'm not working on support related tasks, could you please send this to someone else?

Thanks,
Tamás

**Comment by peterborkuti** [comment]
It is ok on next week.

**Comment by moltam89** [comment]
Probably I'll work on my project on the next week as well.

**Pull request closed without merging**
