### PR TITLE
LPS-132444

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@moltam89 see my comments in https://github.com/brianchandotcom/liferay-portal/pull/107612

**Comment by moltam89** [comment]
ci:test:stable

**Comment by moltam89** [comment]
ci:test:relevant

**Comment by moltam89** [comment]
ci:test:staging

**Comment by moltam89** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/108144

**Pull request closed without merging**
