### PR TITLE
Test LPS-101030

### PR DESCRIPTION
**Pull request by moltam89**

### CODE REVIEW

**Comment by moltam89** [comment]
ci:test

**Comment by JoyceWang08211** [comment]
The above failures are not related to the current commit.

**Comment by JoyceWang08211** [comment]
ci:retest

**Comment by JoyceWang08211** [comment]
ci:stop

**Comment by JoyceWang08211** [comment]
ci:test:staging

**Comment by JoyceWang08211** [comment]
1. The central-requirements-jdk8 failure has been fixed under https://github.com/liferay/liferay-portal/commit/51bda322427b08d49da48109998195297939cc7c.

2. The functional test failure is a flaky.

**Comment by moltam89** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/80921

**Pull request closed without merging**
