### PR TITLE
LPS-75064 Set "application/zip" as content type for .lar files to avoid unnecessary metatada extraction by Tika

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @moltam89 

Could you please check this pull request?

Thank you!

Best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:reopen

**Comment by IstvanD** [comment]
ci:retest

**Comment by moltam89** [comment]
Hi István,

if i understand it correctly, the root cause of the problem is that the 
__detector.detect(tikaInputStream, metadata);_  call in [MimeTypesImpl](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/util/MimeTypesImpl.java#L121) takes a lot of time, therefore the fix bypasses it by assuming the the contentType is zip all the time.

What is weird for me, that when I uploaded a simple test LAR file, the __detector.detect__ method was called twice, once from the ImportLayoutsMVCActionCommand class, which you bypassed and also once when the file size validation was running.
For me it means that even if I'd apply the fix, the type detection would still take a lot of time.

Furthermore, I think we'll face the same problem if e.g. we would upload a LAR file to the Documents and Media portlet.
I think this fix just hides the real problem, can't we "teach" tika to detect LAR files faster?

Also it is possible to drag and drop files with different extensions e.g. by an accident, it seems a bit dangerous to me to assume that the content type is zip anyways.

Thanks,
Tamás

**Comment by IstvanD** [comment]
Hi @moltam89 

Thank you for reviewing the pull.

> I think this fix just hides the real problem, can't we "teach" tika to detect LAR files faster?

This was indeed the original idea, but it deemed too complex, and a simpler solution was choosen
https://github.com/robertoDiaz/liferay-portal/pull/607

**Comment by moltam89** [comment]
Well, I'd prefer the complex fix, if it solves the issue properly :).

> What is weird for me, that when I uploaded a simple test LAR file, the detector.detect method was called twice, once from the ImportLayoutsMVCActionCommand class, which you bypassed and also once when the file size validation was running.
For me it means that even if I'd apply the fix, the type detection would still take a lot of time.

Am I wrong here?

Also these test failures seem related.

Thanks,
Tamás

**Pull request closed without merging**
