### PR TITLE
LPS-99297 View Staging doesn't mean that we should allow perform actions.We should filter them and do not allow users without manage permission relaunch or remove existing elements.

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:staging

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
hi @moltam89 

What is the status of this ticket?

**Comment by moltam89** [comment]
Hi @robertoDiaz ,

I've just started to review this PR.
I think the LPS number - LPS-98654 - is wrong, it seems another issue.

Could you please check it?

Thanks,
Tamás

**Comment by moltam89** [comment]
Checking the branch name I found LPS-99297.

Isn't this the same issue as LPP-27510 which was considered the expected behavior?

Thanks,
Tamás

**Comment by robertoDiaz** [comment]
Hi @moltam89 

Yes, the LPS is wrong, I could change it.

> Isn't this the same issue as LPP-27510 which was considered the expected behavior?

No. I'm allowing to see the staging option (in order to provide information to users that could manage pages, since the publication status is relevant to them, but I'm disabling the option of perform actions to users that do not have "manage_staging" permission.

**Comment by moltam89** [comment]
Hi @robertoDiaz ,

Thanks for the explanation.

Could you please update the expected result on the LPS? 
Right now it sounds like we want to remove the Staging option.

Thanks,
Tamás

**Comment by moltam89** [comment]
Also, with Manage Pages permission only the control panel doesn't show up, could you please specify which permissions are necessary exactly?

Thanks,
Tamás

**Comment by moltam89** [comment]
ci:test

**Comment by moltam89** [comment]
HI @robertoDiaz ,

I don't think that this fix is complete.

I miss the permission checks on the backend, probably it's not enough to hide the buttons on the UI only.

According to our [documentation ](https://portal.liferay.dev/docs/7-2/user/-/knowledge_base/u/managing-permissions) the Manage Staging permission "Hides/shows the Staging Configuration menu in the Site Administration → Publishing → Staging → Options (Options) menu."

The current fix uses it for other purposes.

Best,
Tamás

**Comment by robertoDiaz** [comment]
Hi @moltam89 

I'm going to add the permission checks to the service layer.

About:

> According to our documentation the Manage Staging permission "Hides/shows the Staging Configuration menu in the Site Administration → Publishing → Staging → Options (Options) menu."

It means that our documentation is not accurate. The staging configuration is not only shown when the user has Manage Staging permission (in fact this is the root cause of the ticket). In this case, if the user has MANAGE PAGES permission, he could see the Staging Configuration menu.

In order to provide a  temporal fix to the customer, what is the expected behaviour when a user has MANAGE_PAGES permission without MANAGE_STAGING?

Thanks!

**Comment by moltam89** [comment]
Hi @robertoDiaz ,

The doc also states that 
"View Staging: if Publish Staging, Manage Pages, Manage Staging, or Update permissions are not granted, hides/shows the Staging app in the Site Administration menu."

In LPP-27510 it was confirmed that because of legacy reasons Manage Page permission controls the visibility of the Staging menu.

To me it seems that Manage pages permission is basically the same as View Staging, see the code in [GroupPermissionImpl ](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/service/permission/GroupPermissionImpl.java#L211-L226).

Best,
Tamás

**Comment by robertoDiaz** [comment]
Hey @moltam89 

The key poing is that if View Staging should let users perform actions such rerun tasks or delete them.

If that's the case, why couldn't they create new ones??

**Comment by moltam89** [comment]
Hi @robertoDiaz ,

I don't think that with View permission only users should be able to rerun/delete tasks.

We should check Publish Staging permission for these.
Also, Publish Staging should be granted in order to reach the Publish Templates section.

Next time please create a PTR ticket instead for behavior clarification, as these conversations are hardly traceable.

cc @zsigmondrab

Thanks,
Tamás

**Comment by robertoDiaz** [comment]
Hi @moltam89 

You've confirmed that the analysis I had made is ok (we should show the Staging section but hide the actions depending on the user permissions) and the only thing I have to change is an implementation detail (use the publish staging permission instead of manage_staging) 

So, in this case, I don't find how a PTR could help.

The only reason why I asked about a behaviour clarification is because the first comment of the review (https://github.com/moltam89/liferay-portal/pull/521#issuecomment-519567626) was not clear for me.

Regards.

**Pull request closed without merging**
