### PR TITLE
LPS-119920 Orphaned pages after page variation is deleted from site builder, but not from navigation menu. 

### PR DESCRIPTION
**Pull request by vendeltoreki**
Hi @moltam89 ,

I'm forwarding Attila's PR ( https://github.com/vendeltoreki/liferay-portal/pull/107 ) to you.

Please review the changes.

Thanks,
Vendel

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by moltam89** [comment]
As we discussed, please sed this directly to Brian.

Thanks,
Tamas

**Pull request closed without merging**
