### PR TITLE
LPS-99407 Make the usage of remote site's virtual host configurable

### PR DESCRIPTION
**Pull request by hudakl**
Hi Tomcsi,

Could you please review my solution suggestion for LPS-99407?

Thanks,
Laci

### CODE REVIEW

**Comment by moltam89** [comment]
ci:test

**Comment by moltam89** [comment]
Hi @hudakl ,

Could you please check if the failing tests are related to the current fix?

Thanks,
Tamás

**Comment by hudakl** [comment]
I added a source format and rebased the fix.
The other test results doesn't appear to be related.

**Comment by moltam89** [comment]
Hi @hudakl ,

It's not a good practice to add SF commits to our own code.
Could you please merge the SF related changes to the appropriate commit?

Thanks,
Tamás

**Comment by hudakl** [comment]
@moltam89 updated

**Comment by moltam89** [comment]
ci:test

**Comment by hudakl** [comment]
Hi Tomcsi,


Do you have any updates on the review?

Thanks,
Laci

**Comment by moltam89** [comment]
Hi Laci,

Won't we reintroduce the problem describe in LPS-72443 with this fix?

Thanks,
Tamás

**Comment by hudakl** [comment]
I haven't experienced that issue during my tests.

**Comment by moltam89** [comment]
It would be nice to know what fixed the issue, otherwise we can't be sure that we won't reintroduce the original problem.

**Comment by moltam89** [comment]
Forwarded to https://github.com/vendeltoreki/liferay-portal/pull/23.

Thanks,
Tamás

**Pull request closed without merging**
