### PR TITLE
Lps 94690 2

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @knchau

Notes from Kim:
> https://issues.liferay.com/browse/LPS-94690
> 
> The issue is when the site is staging. At every page load of the Control Panel, the local server would send a request to the remote server. This can cause the site to hang because the request is sent in GroupServiceHttp.getGroupDisplayURL. The timeout can take 30 seconds. Issue can also be seen on page view with the button "Go to Remote Live". 
> 
> The fix involves an ajax call for fetching the URL after everything else is loaded and rendered. But while everything is rendering, the Control Panel will contain a spinner until everything is completely loaded. Whereas the button will also be loaded after page view load. 
> 
> Within the ajax call, it would check for a remote connection and return the live URL. If the remote connection is severed, I would add its respective SessionError. Upon connection failure, it would enter failureCallback. This function displays the tooltip error. If there is no remote connection (i.e. Staging Configuration is set to Local Live) and you're on the live page, the session error would be empty and the element link would be null so it would apply the appropriate attributes.
> 
> This fix won't affect the general performance because the ajax call is done after everything else is rendered.

### CODE REVIEW

**Comment by moltam89** [comment]
Hello,

@vendeltoreki will review this PR.

Thanks,
Tamás

**Comment by vendeltoreki** [comment]
Hi @knchau , @SamZiemer , @moltam89 ,

I've checked out and built this branch (rebased on a recent master cb34aedc8a1b7fc01bada03ccf023a13e2712ac6 ), but did not include the other pull ( https://github.com/moltam89/liferay-portal/pull/551 ).

I started remote staging on `localhost:8080`, remote live on `localhost:9080`. Setting up and publication was successful, but the links don't seem to work. They display various error messages in tooltip:
* "The connection to the remote live site cannot be established due to a network problem." on the admin panel.
* "An unexpected error occurred." on the top staging bar.

And a JS error in console (Chrome):
> Access to XMLHttpRequest at 'http://localhost:9080/web/remotelive2' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Is this the right way to test it or am I doing something wrong?

Also, I debugged into the code and it seems like we are not avoiding service calls to live during rendering:
* `StagingImpl.getRemoteSiteURL(..)` is called twice in staging, which calls
* `GroupServiceImpl.getGroupDisplayURL(long, boolean, boolean)` on the remote live server

When I shut down remote live, the page rendering in staging still slows down significantly.

I have one more question: I don't know whether you have considered a more simplistic approach.
Generate a static link in staging, without calling live, adding just a groupId to the link, and let live server figure it out where it should redirect. This means that a URL resolver or filter should be implemented, which redirects to the right URL on staging. I don't know yet whether this would be completely feasible, it's just the first idea I could think of.

As I understand, these are the requirements from the product perspective:
* Don't slow down any rendering in staging, since live server can respond slowly, or can be completely down.
* Live server can be separated temporarily from staging. It can happen that they can't reach each other on a company's internal network (of course, this also makes publication impossible), but both are up and running and users can reach both from external links.
* Calling to another domain in JS might be problematic
* Live server monitoring (?): I'm not sure whether we really need this. It's a nice to have feature, since users can always see whether there are any network connection problems between staging and live servers. However, this introduces extra complexity, that we have to handle: make sure we don't overload the server, but the URLs have to be up to date, etc.

I've looked into most of the previous pulls and tickets, but could not read everything. I've read about the limitation of background tasks: they can't safely monitor live server, since a user is required to make these service calls, and it might happen that even admins can't see everything in live.

I would like go with the most simple solution, if possible.
Please let me know what you think.

Thanks,
Vendel

**Comment by knchau** [comment]
Updated PR: https://github.com/vendeltoreki/liferay-portal/pull/20

**Comment by knchau** [comment]
ci:close

**Pull request closed without merging**
