### PR TITLE
LPS-99297 Prepare the test to the new logic: We should populate the threadLocal with the permissionChecker of the user.

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
si:test:relevant

**Comment by robertoDiaz** [comment]
ci:test:staging

**Comment by robertoDiaz** [comment]
Hey @moltam89 

What is the status of this??

**Comment by robertoDiaz** [comment]
ci:test:staging

**Comment by moltam89** [comment]
Hi @robertoDiaz ,

I haven't started the review yet, because of the test failures.
Do you think those are unrelated?

Thanks,
Tamás

**Comment by robertoDiaz** [comment]
ci:test:staging

**Pull request closed without merging**
