### PR TITLE
LRQA-66864 | master

### PR DESCRIPTION
**Pull request by JoyceWang08211**
https://issues.liferay.com/browse/LRQA-66864

@moltam89 Here is what I mentioned input portlet value in backend. I've test this PR on local and it works well. Could you take a look if it make sense? I'm not sure which modification is better comparing with Yang Cao's PR. It depends on you. Thanks in advance.

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:test:sf

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @JoyceWang08211, I find a way to set attribute to serviceContext via cURL Http Request.
The solution is same with https://github.com/moltam89/liferay-portal/pull/613
See https://github.com/liferay-echo/liferay-portal/pull/4390

**Comment by moltam89** [comment]
https://github.com/liferay-echo/liferay-portal/pull/4390

**Pull request closed without merging**
