### PR TITLE
[Technical Support] LPS-66606 and LPS-66603 and LPS-66818

### PR DESCRIPTION
**Pull request by yuhai**
cc @daledotshan

Hi Tamas,

I hope that you are well. Giros told me sent the pull request to review because he is on vacation during this week. The pull request extends from https://github.com/giros/liferay-portal/pull/41.

Due to LPS-66606 uses new created LayoutRevisionThreadLocal class (in LPS-66603), this commit includes three different fix (I need to firstly fix LPS-66818 so that LPS-66603 and LPS-66606 are right). Please refer to the below explanation.

**LPS-66818:** in origin code, if layoutRevision exist head(true) version, it will fetch this reversion. However, in UI, if I update some reversions based on head(true) version, it will keep inherit relation and latestLayoutRevision might be "draft" state. At this time, if import same layout, it should fetch latestLayoutRevision "draft" as returned layoutRevision so that import can based on latestLayoutRevision to match the layout and inherit relation(parentLayoutrevisionId) won't be broken.

**LPS-66603:** When import two pages which exists portlets, we should re-setLayoutRevisionId so that import the second page can't affect the first imported page. Actually, LayoutRevisionThreadLocal came from the commit "LPS-22777 Can not save metadata in asset publisher configuration in staging", and this was SF/deleted(14245f9f9791cada394963dfa33fc86adcb011e8) to LayoutRevisionLocalServiceImpl class. Please refer to the below explame:

Please refer to the below explame:
Assumption: In lar, there are two layouts "page1" and "page2", in "page1", exist web content display portlet. In "page2", exist "asset publisher portlet". When import web content display, LayoutRevisionLocalServiceImpl will set "_layoutRevisionId.set(layoutRevision.getLayoutRevisionId());". At this time, layoutRevision is "page1" related data. And then when import "asset publisher portlet", due to we don't reset the value in _layoutRevisionId, it will get "page1" layoutRevision data. At here, it should get "page2" layoutRevision data. So we need to reset the value so that when import more than one layout and this can works well.

Based on Giros's guide (https://github.com/giros/liferay-portal/pull/41#issuecomment-227766156), In the import process, for one layout include multi portlets, keep only one layoutRevision data generated when import these portlets portletPreferences.

**LPS-66606:** When import layout to enabled layoutRevision staging site, we should create one new layoutrevision data instead of directly updating data in layout table. Because when edit one layout in staging site on UI, it won't update layout table and it will create new layoutrevision data in layoutrevision table. Please refer to LPS-66606's description to know master and 6.2.x different behavior. On master, when import one blank page and this page will include some default portlets(for example, com_liferay_portal_search_web_portlet_SearchPortlet), so it won't have 6.2.x behavior. This fix will definely fix the issue on ee-6.2.x. Because on ee-6.2.x, for one empty page, it doesn't include portlets in import lar.

Thanks in advance,

Regards,
Hai

### CODE REVIEW

**Comment by moltam89** [comment]
ci:retest

**Comment by moltam89** [comment]
Hi Hai,

I haven't had time to review all the three LPSs yet, I checked the code related to LPS-66818 only.

As far as I can see, the main idea behind the fix for LPS-66818 is to find the draft revisions as well.

I guess it's OK for the current use case, but is it OK otherwise?
This change could affect other parts of the Portal as well, where the logic requires the latest head revision.
e.g.:
If I turn on page versioning and export the Site, I would expect that the latest head revision will be exported. However, after the fix, the latest draft version will be used.

Could you please check it?

In the meantime I'll continue the review, to get the whole image.

Thanks,
Tamás

**Comment by yuhai** [comment]
ci:retest

**Comment by yuhai** [comment]
Hi Tamás,

I append one commit to solve your mentioned issue regarding export case. 
Please refer to the commit: https://github.com/moltam89/liferay-portal/pull/357/commits/e6499d7975ed2ea22add02e825aaeb972af76202

I think only import progress should use this logic. 

For LayoutRevision data doesn't own head(true), should they been exported?
For example, 
1. create site "site1" and enable remote staging(enable page revision).
2. add two pages "page1" and "page2".
3. make page1 layoutRevision's state for approved by clicking "Ready for Publication".
4. export site1, "page2" also can be exported.
At this point, I think this behavior should be wrong. we shouldn't export these pages which don't include head(true) layoutRevision. right? If yes, this is new issue but it doesn't affect the fix.

Regards,
Hai

**Comment by moltam89** [comment]
ci:retest

**Comment by moltam89** [comment]
ci:retest

**Comment by moltam89** [comment]
Hi @yuhai ,

as this issue is quite complicated, I talked to the engineers to ask their opinion.

They said that generally the import process should work the same way as when we edit a layout from the UI, so I focused on this while I was reviewing this pull request.

**LPS-66818:**
I'm not sure if it's a good idea to introduce a new logic to find the latest revision.
When we edit e.g. the layout's name from the UI, the *_getLayoutRevision* method will find the latest revision. I think we should try to reuse this existing logic during the import process as well, otherwise there is no guarantee that editing a layout from the UI and editing a layout during the import process will have the same result.

**LPS-66606:**
I think we should keep the logic which updates the layout, otherwise the layout related changes won't have any affect. e.g. if we change the layout's type from Portlet to something else, if we doesn't update the layout during the import process it won't be applied.

We should check how this use case is handled when we edit the layout form the UI and apply the behavior for the import process.

Please let me know if you have any questions.

Thanks,
Tamás

**Comment by yuhai** [comment]
Hi Tamás,

For now, I have one question regarding LPS-66818:

**LPS-66818:**
In the import progress, the original logic will directly fetch latest head(true), it skips layoutsetbranch choose. If we follow with UI operations, the original way also should will be wrong. 

For example:
If I use another user(user:hai) who doesn't create layoutsetbranch author (user:test). When use user:hai to import the lar, if we follow with ui logic, it should import the lar into MasterLayoutSetBranch (main-variation). At this time, lastLayoutRevision's layoutSetBranchId is not main-variation.

However, use user:hai login, and he can add new layoutRevision based on other layoutSetBranchId besides MasterLayoutSetBranch (main-variation).

**So if it follow with UI, it should be confused for end user because this import will apply on MasterLayoutSetBranch**. At this point, I think it is better to follow with the original logic. What do you think on this point?

**LPS-66606:**
 The fix missed the function. If the fix used this method from https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/service/impl/LayoutLocalServiceStagingAdvice.java#L233-328 and it will keep consistent with UI. I will further check this.

Regards,
Hai

**Comment by yuhai** [comment]
Hi Tamás,

I hope that you are well. 

For now, I am working on LPS-66606 correction. I will use the below updateLayout method to match with UI operation.
**updateLayout:**
https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/service/impl/LayoutLocalServiceStagingAdvice.java#L233-328 

In this correction progress,  I need to handle with some params about (serviceContext,iconImage,iconBytes). Basically, I finish this correction and need to test it. I should update this pull request tomorrow.

Regards,
Hai

**Comment by moltam89** [comment]
Hi Hai,

sorry for the late response, I consulted with the engineers again.

**LPS-66818:**
If I understand it correctly, when we edit a layout from the UI, _serviceContext_ won't be null, so a different logic will be used than when we import a LAR file. 
Can't we generate a proper serviceContext object during the import process? We could push it to ServiceContextThreadLocal, so  the same logic will be used.

Regards,
Tamás

**Comment by yuhai** [comment]
Hi Tamás,

I just update the correction, please refer to the commit:
https://github.com/moltam89/liferay-portal/pull/357/commits/d25c29456ebc3546fe3b4cb70b98c0c84b0d6a58

**LPS-66606**
For new add commit, I want to do some explanations:
1.In updateLayout method, why use layout.getNameMap() instead of importedLayout.getNameMap(). 

Because importedLayout is wraplayout, when importedLayout.getNameMap() execute, it will invoke LayoutRevisionModelImpl.getNameMap(), the detailed logic is in LayoutStagingHandler.invoke()

2.generated serviceContext won't cause LayoutLocalServiceStagingAdvice.updateLayout() vaild failed. for example:
```
layoutLocalServiceHelper.validate(
	groupId, privateLayout, layoutId, parentLayoutId, name, type,
	hidden, friendlyURLMap, serviceContext);
```

when enter https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/service/impl/LayoutLocalServiceHelper.java#L269-277

Due to we can't add this kind(type: control_panel, shared_portlet) layout in UI, we won't export them.
Please  refer to this commit from https://github.com/juliocamarero/liferay-portal/pull/3668/commits/f964a22a939df3087915f70e9e0939826821bfc2

3.After applying this fix, you also will find layout data (name field) will be update. But this is not caused by this part. It is caused by LayoutImportController.updateLayoutPriorities() from https://github.com/liferay/liferay-portal/blob/master/modules/apps/web-experience/export-import/export-import-service/src/main/java/com/liferay/exportimport/controller/LayoutImportController.java#L1233-1234

This will wrap this layout. When _layoutLocalService.updateLayout(layout), it will skip below code part and use LayoutRevisionModelImpl method.

https://github.com/liferay/liferay-portal/blob/master/modules/apps/web-experience/export-import/export-import-service/src/main/java/com/liferay/exportimport/controller/LayoutImportController.java#L1233-1234

However, update Layout table data won't affect the case. In ee-6.2.x, for one empty page, it doesn't include portlets in import lar. So this fix only need to add related layoutRevision data and it will solve customer's issue. 

**LPS-66818:**
> Can't we generate a proper serviceContext object during the import process? We could push it to ServiceContextThreadLocal, so the same logic will be used.

From my understanding, you mean we generate a proper serviceContext object for LPS-66606. Because in the import progress and serviceContext won't be null, please refer to https://github.com/liferay/liferay-portal/blob/master/modules/apps/web-experience/export-import/export-import-service/src/main/java/com/liferay/exportimport/controller/LayoutImportController.java#L418-426

Sorry for the long explanation. :)

Regards,
Hai

**Comment by yuhai** [comment]
ci:retest

**Comment by moltam89** [comment]
Hi @yuhai ,

**LPS-66606**:
I'm not sure that it is the right approach to handle the issue, it seems a bit fragile to me that certain parameters are calculated twice. 
Probably a better solution would be to implement the changes which separates the update logic for the layout and the layoutrevision in _LayoutLocalServiceStagingAdvice_.

**LPS-66818:**
I still think that we shouldn't add new logic to the*_getLayoutRevision** method, it would be better to use the already existing one.

I'm cc'ing @danielkocsis as I discussed this issue with him, Dani feel free to add your thoughts here.

Thanks,
Tamás

**Comment by daledotshan** [comment]
@danielkocsis
Hey Dani,
Could you please give a direction about this issue? This issue is for a ee customer, the LPP ticket has been opened for long time.

Thanks,
Dale

**Comment by danielkocsis** [comment]
Hey @daledotshan,

I am totally on the same page with @moltam89, so I would like to ask you guys please follow his guidance to make sure we commit the proper solution to the master branch. I know it is urgent for you since it is a customer ticket, but it is also important to have a good solution not just a working or quick one.

thanks,
Daniel

**Comment by yuhai** [comment]
Hi Tamás,

LPS-66818:
I use StagingUtil.getRecentLayoutRevisionId() and it should get lastLayoutRevision. Is this right?

LPS-66606:
I might misunderstand your meaning. Do you mean that we should separates the update logic for the layout and the layoutrevision in LayoutLocalServiceStagingAdvice.updateLayout(15 arguments) method, then we add case judgement: for import progress, it can skip some logic(validate, setExpandoBridgeAttributes)? Could you please explain the detail for me?

Regards,
Hai

**Pull request closed without merging**
