### PR TITLE
Lps 94690 1

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @knchau

Notes from Kim:
> https://issues.liferay.com/browse/LPS-94690
> 
> The issue is when the site is staging. At every page load of the Control Panel, the local server would send a request to the remote server. This can cause the site to hang because the request is sent in GroupServiceHttp.getGroupDisplayURL. The timeout can take 30 seconds.
> 
> The fix makes a ajax call for fetching the URL after everything else is loaded and rendered. But while everything is rendering, the Control Panel will contain a spinner until everything is completely loaded.
> 
> Within the ajax call, it would check for a remote connection and return the live URL. If the remote connection is severed, I set the property `isConnected` to false; otherwise, the default value is true. Upon connection failure, it would enter `failureCallback`. This function displays the tooltip error. If there is no remote connection (i.e. Staging Configuration is set to Local Live) and you're on the live page, the property `isConnected` is defaulted true and the live group URL is a blank string, so it would apply the appropriate [attributes](https://github.com/SamZiemer/liferay-portal/commit/fa1ae2dab46e60477838218ab0a467a85a251ffc#diff-2db79331dcd02f15d22749213538877fR100-R103).
> 
> This fix won't affect the general performance because the ajax call is done after everything else is rendered.

### CODE REVIEW

**Comment by moltam89** [comment]
Hi @knchau , @SamZiemer ,

I see that there is another [pull ](https://github.com/moltam89/liferay-portal/pull/526)with the same ticket which got stuck in my queue.

Can I ignore that and review this instead?

Thanks,
Tamás

**Comment by moltam89** [comment]
ci:test

**Comment by SamZiemer** [comment]
Hi @moltam89,

Yes, the previous one can be closed out, thank you!

**Comment by knchau** [comment]
Hi @moltam89,

Do you have an ETA when this pr can be reviewed?

Thank you!

**Comment by moltam89** [comment]
Hi @knchau ,

Sorry for the delay. I'll check this PR next week.

Thanks,
Tamás

**Comment by moltam89** [comment]
Hi @knchau ,

I'm sorry, but I have to postpone this PR again for the next week (tomorrow is a national holiday in Hungary).
I know you had to put a lot of effort to fix this issue and I keep postponing this task.
Right now I feel that I'd make it even worth if I'd try to review this in a hurry.

Sorry again for the inconvenience.

Best,
Tamás

**Comment by knchau** [comment]
@moltam89, no worries, thank you for letting me know!

**Comment by moltam89** [comment]
Hi @knchau ,

Do I understand it correctly that after this fix, when we are navigating on the Control Panel, basically on each click the Group will be updated?
If yes, I think that might be a problem.

Thanks,
Tamás

**Comment by knchau** [comment]
Hi @moltam89,

Your understanding is correct that when navigating on the Control Panel each click the Group will be updated. I could remove updateGroup, if that is the only issue?

Thanks!

**Comment by moltam89** [comment]
Hi @knchau ,

I was also wondering whether we have the same issue on the page view.
I mean when we navigate to a page, there is also a button which navigates to the Live Site.

Thanks,
Tamás

**Comment by knchau** [comment]
Hi @moltam89,

I am assuming that this is occurring when the user is on the Staging site? Although I am still unclear about the page view issue, can you further explain the issue that you are experiencing? 

Is there absence of a button that leads to the Remote Live site?

Thank you!

**Comment by moltam89** [comment]
Hi @knchau ,

Sorry for not being clear.

If we enable remote Staging, at the top of any widget pages there is a "Go to Remote Live" button.
As far as I can see, the URL is generated by the same [getRemoteSiteURL ](https://github.com/liferay/liferay-portal/blob/master/modules/apps/staging/staging-bar-web/src/main/java/com/liferay/staging/bar/web/internal/portlet/StagingBarPortlet.java#L273) method, which is used in the SiteAdministrationPanelCategoryDisplayContext class.

Thanks,
Tamás

**Comment by knchau** [comment]
Hi @moltam89,

Thank you for the clarification, I see what you are saying now. Do you have any suggestions on how a resolve should be implemented for this?

[getRemoteSiteURL](https://github.com/liferay/liferay-portal/blob/master/modules/apps/staging/staging-bar-web/src/main/java/com/liferay/staging/bar/web/internal/portlet/StagingBarPortlet.java#L273) method will probably need to be removed from the render method, so the remote site URL will have to be defined elsewhere is my first thought. 

Best,
Kim

**Comment by moltam89** [comment]
Hi @knchau ,

I don't have any specific solution in mind.

Best,
Tamás

**Comment by knchau** [comment]
Hi @moltam89,

For that new issue you pointed out, I'm not sure if it would introduce the same concern since the original issue is due to the button's location on the Control Panel so it would occur at every page load whereas this button is only on the site's page. Please let me know your thoughts on this, thank you!

**Comment by moltam89** [comment]
Hi @knchau ,

In my understanding the current issue occurs at two places, therefore I think the final solution should solve both problems.

The control panel issue is is more severe, but navigating to a page on the staging site is also a common use case.

Thanks,
Tamás

**Comment by knchau** [comment]
Updated PR see here: https://github.com/SamZiemer/liferay-portal/pull/705

**Comment by knchau** [comment]
ci:close

**Pull request closed without merging**
