### PR TITLE
LPS-89550

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-89550

Sending to you as per [the comment on the LPS](https://issues.liferay.com/browse/LPS-89550?focusedCommentId=1680701&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1680701), stating this is a cross-cutting issue.  Seems more staging related than USM, but I've reviewed it and everything looks good from my end.
Please let me or @laszlopap know if you have any questions

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by moltam89** [comment]
Hi guys,

please see my comment on the [LPS.](https://issues.liferay.com/browse/LPS-89550?focusedCommentId=1695248&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1695248)

Thanks,
Tamás

**Comment by moltam89** [comment]
I'm reopening this PR, in the meantime we solved the issue in 7.1 by reverting the original LPS which introduced the new option to export import Custom Fields separately, so now it's time to move forward on fixing this in master.

If I understand it correctly, we have a problem here with converting the default data.
Are there any similar problems in 7.1.x?
If I'm not very much mistaken, the ExpandoConverterUtil is used in 7.1 to handle the default data, can't we use this in master as well?

It seems weird to introduce a new third party library and add a lot of new code, as expando export/import was quite stable in 7.1 and previous versions.

Thanks,
Tamás

**Pull request closed without merging**
