### PR TITLE
[TECHNICAL SUPPORT] LPS-89294

### PR DESCRIPTION
**Pull request by knchau**
https://issues.liferay.com/browse/LPS-89294

Hi @moltam89,

Updated how we handle the `ConnectException` in `StagingGroupServiceTunnelUtil._invoke` by throwing the exception and catching it in `SiteAdministrationPanelCategoryDisplayContext.getLiveGroupURL`. This allows it to bypass the generation of a URL with a null string, which would throw a MalformedURLException instead of displaying the NoConnectionException tooltip.

The previous implementation would throw a MalformedURLException here: [StagingImpl.getRemoteSiteURL](https://github.com/knchau/liferay-portal/blob/de5869602b2d93f045e26ffb0ba6f719d3ccbec0/modules/apps/export-import/export-import-service/src/main/java/com/liferay/exportimport/internal/staging/StagingImpl.java#L1754), achieving the behavior you experienced (https://github.com/moltam89/liferay-portal/pull/538#issuecomment-562695380).

/cc @Preston-Crary

### CODE REVIEW

**Comment by knchau** [comment]
ci:test:sf

**Comment by knchau** [comment]
ci:test:relevant

**Comment by knchau** [comment]
ci:test

**Comment by knchau** [comment]
Hi @moltam89,

Customer would like a hotfix for this issue by the end of December. If you approve of this solution as an SDH, please let me know.

Thank you!

**Comment by knchau** [comment]
Hi @moltam89,

Do you have an ETA of when this PR can be reviewed?

Thank you!

**Comment by moltam89** [comment]
Hello,

@vendeltoreki will review this PR.

Thanks,
Tamás

**Comment by knchau** [comment]
Hi @vendeltoreki,

Can you review this PR as is?

Thank you!

**Comment by vendeltoreki** [comment]
Hi @knchau ,

I've started to review this PR (independently from https://github.com/moltam89/liferay-portal/pull/552 ).

**Comment by knchau** [comment]
Hi @vendeltoreki,

Were you able to complete review for this PR?

Thanks!

**Comment by vendeltoreki** [comment]
Hi @knchau,

I think this will work fine. I ran some tests and I only saw one-line errors instead of the large exceptions. Also, the solution seems valid. I will forward this to Brian.

**Comment by knchau** [comment]
Great, thanks @vendeltoreki!

**Comment by vendeltoreki** [comment]
@knchau , I will run a review with @zsigmondrab as well, before forwarding it tomorrow

**Comment by knchau** [comment]
@vendeltoreki, sounds good -- thanks for the update!

**Comment by vendeltoreki** [comment]
Hi @knchau ,

Do you think we can replace the 

> "Connection error: "

 error message in the logs with something more meaningful, like 

> "Unable to connect to remote live: "

We have that in warning message just below it: https://github.com/moltam89/liferay-portal/pull/551/files#diff-f50becfce6ba109cdd42ba35cf1105b0L198-L200

Since this warning is not displayed by default, it would be useful to log it directly in error instead of warning.

**Comment by knchau** [comment]
Hi @vendeltoreki,

Yes, that can be changed - I've updated the PR to display the desired changes. Please let me know if there are any other changes that need to take place.

Thank you!

**Comment by vendeltoreki** [comment]
Thanks @knchau , that looks ok.

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
Forwarded to: https://github.com/brianchandotcom/liferay-portal/pull/83603

Thanks,
Vendel

**Comment by knchau** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
Seems like SF doesn't run the same way on this PR..
fixed it: https://github.com/brianchandotcom/liferay-portal/commit/bfec2cb2ac4465179b4e9387d209bafac2711b62

**Pull request closed without merging**
