### PR TITLE
[TS] LPS-87847 Only hide the message if there are no background tasks

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:staging

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by moltam89** [comment]
Hi @jonathanmccann ,

honestly, I'm not really familiar with the UI part of the staging component, I just searched for 
`<div class="hide incomplete-process-message">`
and I as far as I can see, there are other jsp files using the same code.

Don't we need to fix those places as well?

Thanks,
Tamás

**Comment by jonathanmccann** [comment]
@moltam89 I am in the same boat as you. I'm not sure why this logic was extracted out in the first place but left as is in so many places. I wanted to make a minimal fix to get the extracted logic working properly and see if your team had more insight to the other usages. It seems weird to hide the banner by default but I did find https://github.com/liferay/liferay-portal/blob/master/modules/apps/staging/staging-processes-web/src/main/resources/META-INF/resources/js/main.js#L820 which might be used for these other locations but not the one being fixed on this pull.

**Comment by moltam89** [comment]
Thanks @jonathanmccann!

I've forwarded the fix to https://github.com/rolandpakai/liferay-portal/pull/6.

**Pull request closed without merging**
