### PR TITLE
[TECHNICAL-SUPPORT] LPS-60134

### PR DESCRIPTION
**Pull request by Alec-Shay**
/cc @SamZiemer @joshuacords

Hello Tamás,

Can you take a look at this re-implementation of [LPS-60134](https://issues.liferay.com/browse/LPS-60134) for us? I wasn't sure of any improvements to make to this, but please let us know your thoughts, and if you think this is good to push forward. Thanks!

> **LPS**: https://issues.liferay.com/browse/LPS-60134
> 
> Tested here: https://github.com/joshuacords/liferay-portal/pull/51#issuecomment-461679068
> Note the sf error was related to the name of this method: https://github.com/liferay/liferay-portal/blob/bc250d5444480fa78b8cbee3c581b1d11ee4bfaa/portal-kernel/src/com/liferay/portal/kernel/model/LayoutModel.java#L269
> 
> Notes from @diana-lin
> **Problem**: Re-implement https://github.com/danielkocsis/liferay-portal/pull/504 for Master per discussion from [PTR-608](https://issues.liferay.com/browse/PTR-608).
> 
> > I looked into the history of tickets and also what's in the background, the solution Nathan Shaw proposes should work, especially as we already have this fix available for customers under LPS-60134. As the current open LPP for this issue is LPP-32927, it would be great if someone from the US TS could reimplement this feature for master. After the implementation done, I'd work with Tamas Molnar on reviewing and ensuring that we can prove the Product Team that the risk is low. I've talked to Mate Thurzo and he agreed that this fix could be merged in.
> 
> and [LPP-32927](https://issues.liferay.com/browse/LPP-32927).
> 
> > Hi everyone,
> > 
> > I've talked to Máté and Tamás. Could you please work on reimplementing this for master?
> > 
> > https://github.com/danielkocsis/liferay-portal/pull/504
> > 
> > After the reimplementation done, Tamas Molnar will review and I'll work on documentation to support that there's no risk in bringing this back. We should be able to backport it too.
> > 
> > Thank you,
> > Zsolt
> 
> **Solution**:   Changes from the original PR were applied to different classes due to refactoring of some methods from [LPS-67968](https://issues.liferay.com/browse/LPS-67968).
> 
> - LayoutExportController.java --> LayoutStagedModelDataHandler.java
> - LayoutImportController.java --> StagedLayoutSetStagedModelDataHandler.java
> 
> Details regarding concerns related to Staging discussed here: https://issues.liferay.com/browse/PTR-608.
> 
> ---
> Original notes from @BryanEngler:
> 
> > Hi daniel, I think this might address the issue of re-prioritizing every layout. With this fix, we now only update priorities on layouts where we do know the priority, and on layouts that were deleted. For deleted layouts, they still get moved to the bottom of the list, but this would also occur in a publish of all pages with the current functionality. Let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by Alec-Shay** [comment]
ci:test

**Comment by zsoltbalogh** [comment]
@moltam89 please let me know if you finished the review and should be good to go technically and I'll start to build the risk analysis. Thank you!

**Comment by moltam89** [comment]
ci:test:relevant

**Comment by moltam89** [comment]
Hi @Alec-Shay ,

I haven't checked this fix yet, because I found [LPS-86218](https://issues.liferay.com/browse/LPS-86218) which is a Story ticket about creating a flat list view to pages administration.

I think this new feature might affect the current fix, but I don't know the details yet, I left a comment on LPS-86218 to figure out more.

Let me know if you think these two issues are not connected.

Thanks,
Tamás

**Comment by zsoltbalogh** [comment]
Hi @Alec-Shay,

I'll be doing an investigation tomorrow and post my result here. I have some concerns about the LPS-86218 (found some interesting behavior without having staging enabled) and I'd like to check what to do with that first.

Zsolt

**Comment by moltam89** [comment]
Forwarded to https://github.com/matethurzo/liferay-portal/pull/2497 with minor SF.

Thanks,
Tamás

**Pull request closed without merging**
