### PR TITLE
[Technical Support] LPS-66500 Theme is always propagated from site template to site

### PR DESCRIPTION
**Pull request by zsigmondrab**

### CODE REVIEW

**Comment by moltam89** [comment]
Hey @dsanz , @zsigmondrab ,

I have two remarks about the logic:

- Shouldn't we consider the settings related to the theme?
As far as I can see, the layoutSet's settings will be propagated anyway,  this could be unpleasant, as the theme's settings will be overwritten despite to the new property.

- Probably we should set PortletDataHandlerKeys.THEME_REFERENCE to true in the _if (importData)_ clause, otherwise the theme won't be exported during Site creation either.

Thanks,
Tamás

**Comment by dsanz** [comment]
Hi @zsigmondrab, @moltam89 

you're correct with the THEME_REFERENCE in the other if branch, that one was an oversight from my side.

Regarding layoutset settings, there are a bunch of stuff that it's still being propagated, like javascript and css. Those should be regulated by specific properties if we see that they can have an impact. Anyway, I guess you mean things like color scheme which are stored there too, is this correct?

Best!

**Comment by moltam89** [comment]
Hi @dsanz ,

I meant those settings which are stored in the settings_ column, as far as I can see color scheme has it's own column in the database.

For example if we configure the Site Template and change the Bullet Style from Dots to Arrows on the default theme, according to the new property and the warning message, I would expect that this setting won't have any affect on already existing sites. 
However, the Portal will overwrite the theme's settings.

Tamás

**Comment by dsanz** [comment]
Thanks for pointing this out @moltam89, I see it

I think this behavior is not as easy to implement as we usually process column values in a "shot". But in this case, those properties (either stored in settings or specific columns) would require special treatment. I'll try to figure it out a way to deal with this. The way I see it is to define specific PortletDataHandlerKeys for them, would that make sense to you?

Cheers!

**Comment by moltam89** [comment]
Hi @dsanz ,

I agree that it's not an easy problem, I asked the developers for help .

They said that a quick and dirty solution for the current problem could be to process the settings. We should identify somehow the settings related to the theme and not export/import those.

The long term solution would be introduce LayoutSetStagedModelDataHandler, to handle the problem generally, but I don't think that it's an option for now.

I hope the above is useful to you, I think we will need to involve the developers if there are additional problems.

Thanks,
Tamás

**Comment by dsanz** [comment]
Hi @moltam89 ,

I'm just wondering about the possibility of enabling the LAYOUT_SET_PROTOTYPE_SETTINGS in the same way as the THEME_REFERENCE, so the first time they would be copied, and successive times they would be included in the process only if the property says so.

This would work if and only if:
 * Settings include things that make sense not to propagate
 * We rename the property to another name denoting the new behavior

Makes sense to you?

I'm going to explore this possibility in addition to the settings processing.

I'm also involving @samanzanedo as I'll be some days on PTO and he will take over the ticket in the meantime

Best

**Comment by moltam89** [comment]
Hi @dsanz ,

I'm not familiar with all the possible settings, but even if it makes sense to not propagate any of them, controlling the settings propagation with a new property can be challenging.

For example we already have the property which controls the propagation of the logo, however there is an additional setting under the logo section (Show Site Name) which is also stored in the settings.

I would expect that if I set the property to always propagate the logo, than the related settings are propagated as well, but if the settings are controlled with another property then I won't be able to achieve it.

Tamás

**Comment by moltam89** [comment]
I'm closing this pr for now.

Thanks,
Tamás

**Comment by dsanz** [comment]
Resent to  https://github.com/moltam89/liferay-portal-ee/pull/8

**Pull request closed without merging**
