### PR TITLE
LPS-90127 Create Staging aware ClassTypeReader for JournalArticle

### PR DESCRIPTION
**Pull request by balazssk**
Hi @moltam89 ,
I've made the changes we've discussed.

https://issues.liferay.com/browse/LPS-90127

Can you please review it?
Thanks,

### CODE REVIEW

**Comment by moltam89** [comment]
ci:test

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by balazssk** [comment]
Hi @moltam89 ,
I've checked the failed test locally and found that I can add Basic Web Contents in the Staged Site's Web Content Display Portlet.
Can you please continue with the review?

Thanks

**Comment by moltam89** [comment]
Hi Balázs,

As we discussed, please add the null checks to those methods where the parameter is Group.

In the meantime I'm checking the ClassTypeReader related logic.

Thanks,
Tamás

**Comment by moltam89** [comment]
Hi Balázs,

The new ClassTypeReader looks good to me.

Regards,
Tamás

**Pull request closed without merging**
