### PR TITLE
[TECHNICAL-SUPPORT] LPS-101631 Implement isCustomizable method for LayoutRevision

### PR DESCRIPTION
**Pull request by vendeltoreki**
Hi @moltam89 ,

I've added the implementation of `isCustomizable(..)` to `LayoutRevision`, so it will read this property from `LayoutRevison` when page versioning is active.

I based my implementation on [LayoutImpl.isCustomizable(..)](https://github.com/liferay/liferay-portal/blob/fa9ca59326c29e9729080faf72b49a8e4e49a649/portal-impl/src/com/liferay/portal/model/impl/LayoutImpl.java#L934). The difference is that my version uses the type of the original layout (since layout types can't be changed).

Please review my changes.

Thanks
Vendel

### CODE REVIEW

**Comment by moltam89** [comment]
ci:test

**Comment by vendeltoreki** [comment]
ci:test

**Comment by moltam89** [comment]
Hi Vendel,

As we discussed, I'm not comfortable with merging this change, as I don't know how Page Versioning should behave with Customizable layouts.
I'm afraid that enabling these two features simultaneously could cause problems.

If we really want this fix, I think someone should collect and test all the use cases which can come up, but first we should understand what is the customer's end goal.

Also, please remove the Mobile Device Rules related steps from the LPS, if there isn't any problem with that setting.

Thanks,
Tamás

**Comment by moltam89** [comment]
Hi Vendel,

The customer ticket is still very confusing for me, I'm closing this PR until the picture is clear.

Thanks,
Tamás

**Comment by moltam89** [comment]
Reopening again. :)

**Comment by moltam89** [comment]
ci:test:relevant

**Comment by moltam89** [comment]
ci:test:sf

**Comment by moltam89** [comment]
The fix looks good.

However, as far as I can see, Page Customization doesn't work with Remote Staging properly (without page versioning either).

I don't think that it should be possible to customize the pages in Staging. (Works correctly with Local Staging).
As the customer is using remote staging, in my opinion it would be better to fix this issue as well, or at least we should clarify the expected behavior.
For me in master the "You can customize this page." info message hides the Staging related buttons.

**Note:**
In Live the "Hide Customizable Zones" button is missing. I guess it's another minor issue, it would be great if we could also look into this.

Best,
Tamás

**Comment by vendeltoreki** [comment]
Hi @moltam89 ,

Thanks for the review. I've also noticed that come controls are missing when page versioning and customizable pages are used together. My guess is that the portal can show only one control bar above the content.

**Comment by moltam89** [comment]
Hi Vendel,

**About the current PR:**

I don't like that we're duplicating the _isCustomizable_ method from LayoutImpl, but I couldn't find a better solution.

I tried [reusing the original method](https://github.com/moltam89/liferay-portal/commit/c0d47c7c1ae2859fd23b0f90cb8532f5fb353e59), but this solution doesn't follow the pattern (it looks like that we're already copy-pasted several methods) and also it relies on implementation details.

I let you discuss this with Brian in person. :)

If we can't find a more robust solution, maybe adding a test could ensure that we won't break this functionality in the future.

Thanks,
Tamás

**Comment by vendeltoreki** [comment]
Hi @moltam89 ,

Discussed this with Brian, and the biggest problem is that we are modifying in portal-kernel model, where even minor API version changes are not supported.
I've ran a build and it increased major versions in all of these packages:
1. portal-kernel/src/com/liferay/announcements/kernel/service/persistence/packageinfo
1. portal-kernel/src/com/liferay/document/library/kernel/service/persistence/packageinfo
1. portal-kernel/src/com/liferay/expando/kernel/service/persistence/packageinfo
1. portal-kernel/src/com/liferay/exportimport/kernel/service/persistence/packageinfo
1. portal-kernel/src/com/liferay/portal/kernel/util/packageinfo
1. portal-kernel/src/com/liferay/ratings/kernel/service/persistence/packageinfo
1. portal-kernel/src/com/liferay/social/kernel/service/persistence/packageinfo
1. portal-kernel/src/com/liferay/trash/kernel/service/persistence/packageinfo

We have now more info to decide whether we really want to implement this change or not. My guess is that it can be a valid argument, that this is kind-of an edge case scenario and we don't want to introduce such changes just because of staging.

**Comment by vendeltoreki** [comment]
As an example, I checked [LPS-90400](https://issues.liferay.com/browse/LPS-90400), where a similar version change was required. It seems like the change can go to master, but backports have to be unique fixes, that don't change the kernel model versions.

**Comment by moltam89** [comment]
Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/81360.

Thanks,
Tamás

**Pull request closed without merging**
