### PR TITLE
LPS-89294

### PR DESCRIPTION
**Pull request by Alec-Shay**
https://issues.liferay.com/browse/LPS-89294

Re-sending with changes from: https://github.com/moltam89/liferay-portal/pull/489 (see discussion in the comments)

Notes from previous PR from @knchau: 

> Incorporated suggested changes from previous pull https://github.com/moltam89/liferay-portal/pull/482
> 
> https://issues.liferay.com/browse/LPS-89294
> 
> Notes from previous pull:
> 
> > The issue was that the log error was being thrown on the console. I swallowed the log error if it was a ConnectException and displayed a UI error instead. I had to throw a RemoteExportException to display the proper banner by validating if the remote server is still live. If the connection is severed, it would throw a RemoteExportException for each tab and add a session error. I had to add session error for resourceRequest and renderRequest because the processes tab's view.jsp is called multiple times. renderRequest being used for the first call and resourceRequest for the calls thereafter. Scheduled tab's view.jsp includes the error file because processes tab handles the error message in its liferay-staging tag. The UI between the banner displays are different between the tabs because the processes tab has a management toolbar that has a margin-bottom which provides the gap between the toolbar and the banner whereas the scheduled tab only has the navigation toolbar which does not have any margins so there is no gap between that toolbar and the banner. The banners do not have any particular unique traits to provide a quick fix, so this is determined to be a separate issue.
> 
> And additionally:
> 
> > The fix was to throw an exception when switching between tabs, resulting in a UI display that there is no connection to the remote server. The error log is swallowed from the change to the service_http template.

### CODE REVIEW

**Comment by Alec-Shay** [comment]
ci:test

**Comment by moltam89** [comment]
Hi @knchau ,

Sorry for the late answer.

I discussed this issue with @zsoltbalogh  and we think it would be better if the current ticket would only deal with the logging related changes.

LPS-94690 was opened to monitor the status of the remote bundle, which needs to be solved at the backend, please see [Zsolt's latest comment.](https://issues.liferay.com/browse/LPS-94690?focusedCommentId=1836198&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1836198).

About the logging related changes:
I noticed that only the classes under com.liferay.portal.service.http were regenerated.
Don't we need to regenerate the other *ServiceHttp classes in the modules and under the com.liferay.portlet package?

Thanks,
Tamás

**Comment by knchau** [comment]
Hi @moltam89,

No worries about the late response. 

I wanted some clarification on what is expected of this ticket. If this ticket deals with only logging related changes, would it include the implementation to make the banner appear, or should that be on a newly created ticket or the existing LPS-94690?

And thank you for pointing out the regenerated files, I'll fix that. 

Thanks,
Kim

**Comment by moltam89** [comment]
Hi @knchau ,

I think this ticket should deal with the logging related changes.
I'd open a new ticket for the banner, but LPS-94690 is needed to be solved first - as we'll need a way to identify whether the Live server is down.

Thanks,
Tamás

**Pull request closed without merging**
