### PR TITLE
LPS-133999 Importing Layouts onto a Staging Site with Layout Variations enabled doesn't work properly

### PR DESCRIPTION
**Pull request by moltam89**

### CODE REVIEW

**Comment by moltam89** [comment]
ci:test:sf

**Comment by moltam89** [comment]
ci:test:relevant

**Comment by moltam89** [comment]
ci:test:stable

**Comment by moltam89** [comment]
ci:test:staging

**Comment by mbowerman** [comment]
Hi @moltam89,

This looks good to me. Thanks!

**Comment by moltam89** [comment]
ci:test:relevant

**Comment by moltam89** [comment]
ci:test:staging

**Comment by moltam89** [comment]
Retesting here with a slight modification to not alter the initial staging publication:
https://github.com/moltam89/liferay-portal/pull/621

**Pull request closed without merging**
